// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AggregateOrderBookUpdateFbs extends Table {
  public static AggregateOrderBookUpdateFbs getRootAsAggregateOrderBookUpdateFbs(ByteBuffer _bb) { return getRootAsAggregateOrderBookUpdateFbs(_bb, new AggregateOrderBookUpdateFbs()); }
  public static AggregateOrderBookUpdateFbs getRootAsAggregateOrderBookUpdateFbs(ByteBuffer _bb, AggregateOrderBookUpdateFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AggregateOrderBookUpdateFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long secSid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int seqNum() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean isSnapshot() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public AggregateOrderBookUpdateEntryFbs entries(int j) { return entries(new AggregateOrderBookUpdateEntryFbs(), j); }
  public AggregateOrderBookUpdateEntryFbs entries(AggregateOrderBookUpdateEntryFbs obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int entriesLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }

  public static int createAggregateOrderBookUpdateFbs(FlatBufferBuilder builder,
      long secSid,
      int seqNum,
      boolean isSnapshot,
      int entriesOffset) {
    builder.startObject(4);
    AggregateOrderBookUpdateFbs.addSecSid(builder, secSid);
    AggregateOrderBookUpdateFbs.addEntries(builder, entriesOffset);
    AggregateOrderBookUpdateFbs.addSeqNum(builder, seqNum);
    AggregateOrderBookUpdateFbs.addIsSnapshot(builder, isSnapshot);
    return AggregateOrderBookUpdateFbs.endAggregateOrderBookUpdateFbs(builder);
  }

  public static void startAggregateOrderBookUpdateFbs(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addSecSid(FlatBufferBuilder builder, long secSid) { builder.addLong(0, secSid, 0L); }
  public static void addSeqNum(FlatBufferBuilder builder, int seqNum) { builder.addInt(1, seqNum, 0); }
  public static void addIsSnapshot(FlatBufferBuilder builder, boolean isSnapshot) { builder.addBoolean(2, isSnapshot, false); }
  public static void addEntries(FlatBufferBuilder builder, int entriesOffset) { builder.addOffset(3, entriesOffset, 0); }
  public static int createEntriesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEntriesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endAggregateOrderBookUpdateFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

