// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AmendOrderRequestFbs extends Table {
  public static AmendOrderRequestFbs getRootAsAmendOrderRequestFbs(ByteBuffer _bb) { return getRootAsAmendOrderRequestFbs(_bb, new AmendOrderRequestFbs()); }
  public static AmendOrderRequestFbs getRootAsAmendOrderRequestFbs(ByteBuffer _bb, AmendOrderRequestFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AmendOrderRequestFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int clientKey() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long secSid() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int orderSidToBeAmended() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte orderType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int quantity() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte side() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte tif() { int o = __offset(16); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int limitPrice() { int o = __offset(18); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int stopPrice() { int o = __offset(20); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long timeoutAt() { int o = __offset(22); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int portSid() { int o = __offset(24); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createAmendOrderRequestFbs(FlatBufferBuilder builder,
      int clientKey,
      long secSid,
      int orderSidToBeAmended,
      byte orderType,
      int quantity,
      byte side,
      byte tif,
      int limitPrice,
      int stopPrice,
      long timeoutAt,
      int portSid) {
    builder.startObject(11);
    AmendOrderRequestFbs.addTimeoutAt(builder, timeoutAt);
    AmendOrderRequestFbs.addSecSid(builder, secSid);
    AmendOrderRequestFbs.addPortSid(builder, portSid);
    AmendOrderRequestFbs.addStopPrice(builder, stopPrice);
    AmendOrderRequestFbs.addLimitPrice(builder, limitPrice);
    AmendOrderRequestFbs.addQuantity(builder, quantity);
    AmendOrderRequestFbs.addOrderSidToBeAmended(builder, orderSidToBeAmended);
    AmendOrderRequestFbs.addClientKey(builder, clientKey);
    AmendOrderRequestFbs.addTif(builder, tif);
    AmendOrderRequestFbs.addSide(builder, side);
    AmendOrderRequestFbs.addOrderType(builder, orderType);
    return AmendOrderRequestFbs.endAmendOrderRequestFbs(builder);
  }

  public static void startAmendOrderRequestFbs(FlatBufferBuilder builder) { builder.startObject(11); }
  public static void addClientKey(FlatBufferBuilder builder, int clientKey) { builder.addInt(0, clientKey, 0); }
  public static void addSecSid(FlatBufferBuilder builder, long secSid) { builder.addLong(1, secSid, 0L); }
  public static void addOrderSidToBeAmended(FlatBufferBuilder builder, int orderSidToBeAmended) { builder.addInt(2, orderSidToBeAmended, 0); }
  public static void addOrderType(FlatBufferBuilder builder, byte orderType) { builder.addByte(3, orderType, 0); }
  public static void addQuantity(FlatBufferBuilder builder, int quantity) { builder.addInt(4, quantity, 0); }
  public static void addSide(FlatBufferBuilder builder, byte side) { builder.addByte(5, side, 0); }
  public static void addTif(FlatBufferBuilder builder, byte tif) { builder.addByte(6, tif, 0); }
  public static void addLimitPrice(FlatBufferBuilder builder, int limitPrice) { builder.addInt(7, limitPrice, 0); }
  public static void addStopPrice(FlatBufferBuilder builder, int stopPrice) { builder.addInt(8, stopPrice, 0); }
  public static void addTimeoutAt(FlatBufferBuilder builder, long timeoutAt) { builder.addLong(9, timeoutAt, 0L); }
  public static void addPortSid(FlatBufferBuilder builder, int portSid) { builder.addInt(10, portSid, 0); }
  public static int endAmendOrderRequestFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

