// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class BooleanTypeFbs {
  private BooleanTypeFbs() { }
  public static final byte FALSE = 0;
  public static final byte TRUE = 1;

  public static final String[] names = { "FALSE", "TRUE", };

  public static String name(int e) { return names[e]; }
}

