// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CancelOrderRequestFbs extends Table {
  public static CancelOrderRequestFbs getRootAsCancelOrderRequestFbs(ByteBuffer _bb) { return getRootAsCancelOrderRequestFbs(_bb, new CancelOrderRequestFbs()); }
  public static CancelOrderRequestFbs getRootAsCancelOrderRequestFbs(ByteBuffer _bb, CancelOrderRequestFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public CancelOrderRequestFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int clientKey() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long secSid() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int orderSidToBeCancelled() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long timeoutAt() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean retry() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public byte side() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public boolean force() { int o = __offset(16); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createCancelOrderRequestFbs(FlatBufferBuilder builder,
      int clientKey,
      long secSid,
      int orderSidToBeCancelled,
      long timeoutAt,
      boolean retry,
      byte side,
      boolean force) {
    builder.startObject(7);
    CancelOrderRequestFbs.addTimeoutAt(builder, timeoutAt);
    CancelOrderRequestFbs.addSecSid(builder, secSid);
    CancelOrderRequestFbs.addOrderSidToBeCancelled(builder, orderSidToBeCancelled);
    CancelOrderRequestFbs.addClientKey(builder, clientKey);
    CancelOrderRequestFbs.addForce(builder, force);
    CancelOrderRequestFbs.addSide(builder, side);
    CancelOrderRequestFbs.addRetry(builder, retry);
    return CancelOrderRequestFbs.endCancelOrderRequestFbs(builder);
  }

  public static void startCancelOrderRequestFbs(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addClientKey(FlatBufferBuilder builder, int clientKey) { builder.addInt(0, clientKey, 0); }
  public static void addSecSid(FlatBufferBuilder builder, long secSid) { builder.addLong(1, secSid, 0L); }
  public static void addOrderSidToBeCancelled(FlatBufferBuilder builder, int orderSidToBeCancelled) { builder.addInt(2, orderSidToBeCancelled, 0); }
  public static void addTimeoutAt(FlatBufferBuilder builder, long timeoutAt) { builder.addLong(3, timeoutAt, 0L); }
  public static void addRetry(FlatBufferBuilder builder, boolean retry) { builder.addBoolean(4, retry, false); }
  public static void addSide(FlatBufferBuilder builder, byte side) { builder.addByte(5, side, 0); }
  public static void addForce(FlatBufferBuilder builder, boolean force) { builder.addBoolean(6, force, false); }
  public static int endCancelOrderRequestFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

