// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ChartDataFbs extends Table {
  public static ChartDataFbs getRootAsChartDataFbs(ByteBuffer _bb) { return getRootAsChartDataFbs(_bb, new ChartDataFbs()); }
  public static ChartDataFbs getRootAsChartDataFbs(ByteBuffer _bb, ChartDataFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ChartDataFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long secSid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long dataTime() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int windowSizeInSec() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int open() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int high() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int close() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int low() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int vwap() { int o = __offset(18); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int valueAreaHigh() { int o = __offset(20); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int valueAreaLow() { int o = __offset(22); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte volClusterDirection() { int o = __offset(24); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public VolAtPriceFbs volAtPrices(int j) { return volAtPrices(new VolAtPriceFbs(), j); }
  public VolAtPriceFbs volAtPrices(VolAtPriceFbs obj, int j) { int o = __offset(26); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int volAtPricesLength() { int o = __offset(26); return o != 0 ? __vector_len(o) : 0; }

  public static int createChartDataFbs(FlatBufferBuilder builder,
      long secSid,
      long dataTime,
      int windowSizeInSec,
      int open,
      int high,
      int close,
      int low,
      int vwap,
      int valueAreaHigh,
      int valueAreaLow,
      byte volClusterDirection,
      int volAtPricesOffset) {
    builder.startObject(12);
    ChartDataFbs.addDataTime(builder, dataTime);
    ChartDataFbs.addSecSid(builder, secSid);
    ChartDataFbs.addVolAtPrices(builder, volAtPricesOffset);
    ChartDataFbs.addValueAreaLow(builder, valueAreaLow);
    ChartDataFbs.addValueAreaHigh(builder, valueAreaHigh);
    ChartDataFbs.addVwap(builder, vwap);
    ChartDataFbs.addLow(builder, low);
    ChartDataFbs.addClose(builder, close);
    ChartDataFbs.addHigh(builder, high);
    ChartDataFbs.addOpen(builder, open);
    ChartDataFbs.addWindowSizeInSec(builder, windowSizeInSec);
    ChartDataFbs.addVolClusterDirection(builder, volClusterDirection);
    return ChartDataFbs.endChartDataFbs(builder);
  }

  public static void startChartDataFbs(FlatBufferBuilder builder) { builder.startObject(12); }
  public static void addSecSid(FlatBufferBuilder builder, long secSid) { builder.addLong(0, secSid, 0L); }
  public static void addDataTime(FlatBufferBuilder builder, long dataTime) { builder.addLong(1, dataTime, 0L); }
  public static void addWindowSizeInSec(FlatBufferBuilder builder, int windowSizeInSec) { builder.addInt(2, windowSizeInSec, 0); }
  public static void addOpen(FlatBufferBuilder builder, int open) { builder.addInt(3, open, 0); }
  public static void addHigh(FlatBufferBuilder builder, int high) { builder.addInt(4, high, 0); }
  public static void addClose(FlatBufferBuilder builder, int close) { builder.addInt(5, close, 0); }
  public static void addLow(FlatBufferBuilder builder, int low) { builder.addInt(6, low, 0); }
  public static void addVwap(FlatBufferBuilder builder, int vwap) { builder.addInt(7, vwap, 0); }
  public static void addValueAreaHigh(FlatBufferBuilder builder, int valueAreaHigh) { builder.addInt(8, valueAreaHigh, 0); }
  public static void addValueAreaLow(FlatBufferBuilder builder, int valueAreaLow) { builder.addInt(9, valueAreaLow, 0); }
  public static void addVolClusterDirection(FlatBufferBuilder builder, byte volClusterDirection) { builder.addByte(10, volClusterDirection, 0); }
  public static void addVolAtPrices(FlatBufferBuilder builder, int volAtPricesOffset) { builder.addOffset(11, volAtPricesOffset, 0); }
  public static int createVolAtPricesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startVolAtPricesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endChartDataFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

