// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CommandAckFbs extends Table {
  public static CommandAckFbs getRootAsCommandAckFbs(ByteBuffer _bb) { return getRootAsCommandAckFbs(_bb, new CommandAckFbs()); }
  public static CommandAckFbs getRootAsCommandAckFbs(ByteBuffer _bb, CommandAckFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public CommandAckFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int clientKey() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte commandType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte ackType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createCommandAckFbs(FlatBufferBuilder builder,
      int clientKey,
      byte commandType,
      byte ackType) {
    builder.startObject(3);
    CommandAckFbs.addClientKey(builder, clientKey);
    CommandAckFbs.addAckType(builder, ackType);
    CommandAckFbs.addCommandType(builder, commandType);
    return CommandAckFbs.endCommandAckFbs(builder);
  }

  public static void startCommandAckFbs(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addClientKey(FlatBufferBuilder builder, int clientKey) { builder.addInt(0, clientKey, 0); }
  public static void addCommandType(FlatBufferBuilder builder, byte commandType) { builder.addByte(1, commandType, 0); }
  public static void addAckType(FlatBufferBuilder builder, byte ackType) { builder.addByte(2, ackType, 0); }
  public static int endCommandAckFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

