// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class CommandAckTypeFbs {
  private CommandAckTypeFbs() { }
  public static final byte OK = 0;
  public static final byte NOT_SUPPORTED = 1;
  public static final byte TIMEOUT = 2;
  public static final byte INVALID_PARAMETER = 3;
  public static final byte FAILED = 4;

  public static final String[] names = { "OK", "NOT_SUPPORTED", "TIMEOUT", "INVALID_PARAMETER", "FAILED", };

  public static String name(int e) { return names[e]; }
}

