// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class CommandTypeFbs {
  private CommandTypeFbs() { }
  public static final byte NA = 0;
  public static final byte INIT = 1;
  public static final byte START = 2;
  public static final byte STOP = 3;
  public static final byte SEND_ECHO = 4;
  public static final byte GATHER_PERF_STAT = 5;
  public static final byte WARMUP = 6;
  public static final byte LINE_HANDLER_ACTION = 7;
  public static final byte REFRESH = 8;
  public static final byte EVALUATE_STATE = 9;
  public static final byte RESET = 10;
  public static final byte CAPTURE_PROFIT = 11;
  public static final byte START_TEST_MODE = 12;
  public static final byte STOP_TEST_MODE = 13;
  public static final byte SEND_STRAT_PARAMS = 14;
  public static final byte PLACE_SELL_ORDER = 15;
  public static final byte PRINT_ORDER_INFO_IN_LOG = 16;
  public static final byte PRINT_ALL_ORDER_INFO_IN_LOG = 17;

  public static final String[] names = { "NA", "INIT", "START", "STOP", "SEND_ECHO", "GATHER_PERF_STAT", "WARMUP", "LINE_HANDLER_ACTION", "REFRESH", "EVALUATE_STATE", "RESET", "CAPTURE_PROFIT", "START_TEST_MODE", "STOP_TEST_MODE", "SEND_STRAT_PARAMS", "PLACE_SELL_ORDER", "PRINT_ORDER_INFO_IN_LOG", "PRINT_ALL_ORDER_INFO_IN_LOG", };

  public static String name(int e) { return names[e]; }
}

