// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class DataType {
  private DataType() { }
  public static final byte ALL_ORDER_AND_TRADE_UPDATE = 1;
  public static final byte TRADE_UPDATE = 2;
  public static final byte ALL_POSITION_UPDATE = 3;
  public static final byte PORTFOLIO_POSITION_UPDATE = 4;
  public static final byte ALL_RISK_CONTROL_STATE_UPDATE = 5;
  public static final byte ALL_RISK_CONTROL_STATE_UPDATE_IF_CHANGED = 6;
  public static final byte PORTFOLIO_RISK_CONTROL_STATE_UPDATE = 7;
  public static final byte ALL_EVENT = 8;
  public static final byte ALL_SERVICE_STATUS = 9;
  public static final byte ALL_SUPPORTED_WINDOW_SIZE = 10;
  public static final byte VALIDATION_BOOK = 11;

  public static final String[] names = { "ALL_ORDER_AND_TRADE_UPDATE", "TRADE_UPDATE", "ALL_POSITION_UPDATE", "PORTFOLIO_POSITION_UPDATE", "ALL_RISK_CONTROL_STATE_UPDATE", "ALL_RISK_CONTROL_STATE_UPDATE_IF_CHANGED", "PORTFOLIO_RISK_CONTROL_STATE_UPDATE", "ALL_EVENT", "ALL_SERVICE_STATUS", "ALL_SUPPORTED_WINDOW_SIZE", "VALIDATION_BOOK", };

  public static String name(int e) { return names[e - ALL_ORDER_AND_TRADE_UPDATE]; }
}

