// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class EntityTypeFbs {
  private EntityTypeFbs() { }
  public static final byte INVALID = 0;
  public static final byte SECURITY = 1;
  public static final byte ISSUER = 2;
  public static final byte UNDERLYING = 3;
  public static final byte FIRM = 4;
  public static final byte PORTFOLIO = 5;

  public static final String[] names = { "INVALID", "SECURITY", "ISSUER", "UNDERLYING", "FIRM", "PORTFOLIO", };

  public static String name(int e) { return names[e]; }
}

