// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class EntryTypeFbs {
  private EntryTypeFbs() { }
  public static final byte BID = 0;
  public static final byte OFFER = 1;

  public static final String[] names = { "BID", "OFFER", };

  public static String name(int e) { return names[e]; }
}

