// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class EventValueTypeFbs {
  private EventValueTypeFbs() { }
  public static final byte NULL_VAL = -128;
  public static final byte ANY = 0;
  public static final byte SECURITY_SID = 1;
  public static final byte PREV_UNDERLYING_BID = 2;
  public static final byte PREV_UNDERLYING_ASK = 3;
  public static final byte UNDERLYING_BID = 4;
  public static final byte UNDERLYING_ASK = 5;
  public static final byte PREV_WARRANT_BID = 6;
  public static final byte PREV_WARRANT_ASK = 7;
  public static final byte WARRANT_BID = 8;
  public static final byte WARRANT_ASK = 9;
  public static final byte VELOCITY = 10;
  public static final byte DELTA = 11;
  public static final byte ORDER_SID = 12;
  public static final byte STRATEGY_EXPLAIN = 13;
  public static final byte WARRANT_SPREAD = 14;
  public static final byte TICK_SENSITIVITY = 15;
  public static final byte HIGH_WARRANT_BID = 16;
  public static final byte BEST_SPOT = 17;
  public static final byte WAVG_SPOT = 18;
  public static final byte PREV_WAVG_SPOT = 19;
  public static final byte BUCKET_SIZE = 20;
  public static final byte BUCKET_VIOLATION_TYPE = 21;
  public static final byte TURNOVER_PRICE = 22;
  public static final byte HAS_POSITION = 23;
  public static final byte SIDE = 24;
  public static final byte PRICING_MODE = 25;
  public static final byte GENERIC_EVENT_FLAGS = 26;
}

