// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class EventTypeFbs {
  private EventTypeFbs() { }
  public static final byte UNKNOWN = 0;
  public static final byte THROTTLED = 1;
  public static final byte ORDER_VALIDATION = 2;
  public static final byte ORDER_EXPLAIN = 3;
  public static final byte TO_MAKING_SIGNAL = 4;
  public static final byte VOL_DOWN_SIGNAL = 5;
  public static final byte VOL_UP_SIGNAL = 6;
  public static final byte CONNECTION = 7;

  public static final String[] names = { "UNKNOWN", "THROTTLED", "ORDER_VALIDATION", "ORDER_EXPLAIN", "TO_MAKING_SIGNAL", "VOL_DOWN_SIGNAL", "VOL_UP_SIGNAL", "CONNECTION", };

  public static String name(int e) { return names[e]; }
}

