// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class EventValueFbs extends Table {
  public static EventValueFbs getRootAsEventValueFbs(ByteBuffer _bb) { return getRootAsEventValueFbs(_bb, new EventValueFbs()); }
  public static EventValueFbs getRootAsEventValueFbs(ByteBuffer _bb, EventValueFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public EventValueFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long value() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createEventValueFbs(FlatBufferBuilder builder,
      byte type,
      long value) {
    builder.startObject(2);
    EventValueFbs.addValue(builder, value);
    EventValueFbs.addType(builder, type);
    return EventValueFbs.endEventValueFbs(builder);
  }

  public static void startEventValueFbs(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addValue(FlatBufferBuilder builder, long value) { builder.addLong(1, value, 0L); }
  public static int endEventValueFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

