// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class EventCategoryFbs {
  private EventCategoryFbs() { }
  public static final byte CORE = 0;
  public static final byte EXECUTION = 1;
  public static final byte MARKET_DATA = 2;
  public static final byte STRATEGY = 3;
  public static final byte OTHER = 4;

  public static final String[] names = { "CORE", "EXECUTION", "MARKET_DATA", "STRATEGY", "OTHER", };

  public static String name(int e) { return names[e]; }
}

