// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ExchangeFbs extends Table {
  public static ExchangeFbs getRootAsExchangeFbs(ByteBuffer _bb) { return getRootAsExchangeFbs(_bb, new ExchangeFbs()); }
  public static ExchangeFbs getRootAsExchangeFbs(ByteBuffer _bb, ExchangeFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ExchangeFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int sid() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String code() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer codeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createExchangeFbs(FlatBufferBuilder builder,
      int sid,
      int codeOffset) {
    builder.startObject(2);
    ExchangeFbs.addCode(builder, codeOffset);
    ExchangeFbs.addSid(builder, sid);
    return ExchangeFbs.endExchangeFbs(builder);
  }

  public static void startExchangeFbs(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSid(FlatBufferBuilder builder, int sid) { builder.addInt(0, sid, 0); }
  public static void addCode(FlatBufferBuilder builder, int codeOffset) { builder.addOffset(1, codeOffset, 0); }
  public static int endExchangeFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

