// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class ExecutionTypeFbs {
  private ExecutionTypeFbs() { }
  public static final byte NEW = 0;
  public static final byte TRADE = 1;
  public static final byte CANCEL = 2;
  public static final byte REJECT = 3;
  public static final byte EXPIRE = 4;
  public static final byte AMEND = 5;
  public static final byte TRADE_CANCEL = 6;
  public static final byte CANCEL_REJECT = 7;
  public static final byte AMEND_REJECT = 8;

  public static final String[] names = { "NEW", "TRADE", "CANCEL", "REJECT", "EXPIRE", "AMEND", "TRADE_CANCEL", "CANCEL_REJECT", "AMEND_REJECT", };

  public static String name(int e) { return names[e]; }
}

