// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class GenericFieldTypeFbs {
  private GenericFieldTypeFbs() { }
  public static final byte NULL = -128;
  public static final byte UNKNOWN = 0;
  public static final byte BOOLEAN = 1;
  public static final byte LONG = 2;
  public static final byte NANOSECOND = 3;
  public static final byte DECIMAL3 = 4;
  public static final byte DECIMAL5 = 5;
  public static final byte DECIMAL6 = 6;
}

