// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class LineHandlerActionTypeFbs {
  private LineHandlerActionTypeFbs() { }
  public static final byte CHANGE_MODE_ACCEPT_ON_NEW = 0;
  public static final byte CHANGE_MODE_REJECT_ON_NEW = 1;
  public static final byte CHANGE_MODE_ACCEPT_ON_CANCEL = 2;
  public static final byte CHANGE_MODE_REJECT_ON_CANCEL = 3;
  public static final byte FILL_ALL_LIVE_ORDERS = 4;
  public static final byte PARTIAL_FILL_ALL_LIVE_ORDERS = 5;
  public static final byte EXPIRE_ALL_LIVE_ORDERS = 6;
  public static final byte CANCEL_ALL_TRADES = 7;
  public static final byte RESET = 8;
  public static final byte CHANGE_MODE_MATCH_ON_NEW = 9;
  public static final byte CHANGE_MODE_MATCH_WITH_MULTI_FILLS_ON_NEW = 10;
  public static final byte CHANGE_MODE_PARTIAL_MATCH_ON_NEW = 11;
  public static final byte CHANGE_MODE_PARTIAL_MATCH_WITH_MULTI_FILLS_ON_NEW = 12;

  public static final String[] names = { "CHANGE_MODE_ACCEPT_ON_NEW", "CHANGE_MODE_REJECT_ON_NEW", "CHANGE_MODE_ACCEPT_ON_CANCEL", "CHANGE_MODE_REJECT_ON_CANCEL", "FILL_ALL_LIVE_ORDERS", "PARTIAL_FILL_ALL_LIVE_ORDERS", "EXPIRE_ALL_LIVE_ORDERS", "CANCEL_ALL_TRADES", "RESET", "CHANGE_MODE_MATCH_ON_NEW", "CHANGE_MODE_MATCH_WITH_MULTI_FILLS_ON_NEW", "CHANGE_MODE_PARTIAL_MATCH_ON_NEW", "CHANGE_MODE_PARTIAL_MATCH_WITH_MULTI_FILLS_ON_NEW", };

  public static String name(int e) { return names[e]; }
}

