// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class MarketOutlookType {
  private MarketOutlookType() { }
  public static final byte BULLISH = 1;
  public static final byte BEARISH = 2;
  public static final byte NORMAL = 3;

  public static final String[] names = { "BULLISH", "BEARISH", "NORMAL", };

  public static String name(int e) { return names[e - BULLISH]; }
}

