// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MarketStatsFbs extends Table {
  public static MarketStatsFbs getRootAsMarketStatsFbs(ByteBuffer _bb) { return getRootAsMarketStatsFbs(_bb, new MarketStatsFbs()); }
  public static MarketStatsFbs getRootAsMarketStatsFbs(ByteBuffer _bb, MarketStatsFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MarketStatsFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long secSid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int seqNum() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long transactTime() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int open() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int high() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int low() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int close() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int volume() { int o = __offset(18); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long turnover() { int o = __offset(20); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createMarketStatsFbs(FlatBufferBuilder builder,
      long secSid,
      int seqNum,
      long transactTime,
      int open,
      int high,
      int low,
      int close,
      int volume,
      long turnover) {
    builder.startObject(9);
    MarketStatsFbs.addTurnover(builder, turnover);
    MarketStatsFbs.addTransactTime(builder, transactTime);
    MarketStatsFbs.addSecSid(builder, secSid);
    MarketStatsFbs.addVolume(builder, volume);
    MarketStatsFbs.addClose(builder, close);
    MarketStatsFbs.addLow(builder, low);
    MarketStatsFbs.addHigh(builder, high);
    MarketStatsFbs.addOpen(builder, open);
    MarketStatsFbs.addSeqNum(builder, seqNum);
    return MarketStatsFbs.endMarketStatsFbs(builder);
  }

  public static void startMarketStatsFbs(FlatBufferBuilder builder) { builder.startObject(9); }
  public static void addSecSid(FlatBufferBuilder builder, long secSid) { builder.addLong(0, secSid, 0L); }
  public static void addSeqNum(FlatBufferBuilder builder, int seqNum) { builder.addInt(1, seqNum, 0); }
  public static void addTransactTime(FlatBufferBuilder builder, long transactTime) { builder.addLong(2, transactTime, 0L); }
  public static void addOpen(FlatBufferBuilder builder, int open) { builder.addInt(3, open, 0); }
  public static void addHigh(FlatBufferBuilder builder, int high) { builder.addInt(4, high, 0); }
  public static void addLow(FlatBufferBuilder builder, int low) { builder.addInt(5, low, 0); }
  public static void addClose(FlatBufferBuilder builder, int close) { builder.addInt(6, close, 0); }
  public static void addVolume(FlatBufferBuilder builder, int volume) { builder.addInt(7, volume, 0); }
  public static void addTurnover(FlatBufferBuilder builder, long turnover) { builder.addLong(8, turnover, 0L); }
  public static int endMarketStatsFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

