// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class MessagePayloadFbs {
  private MessagePayloadFbs() { }
  public static final byte NONE = 0;
  public static final byte CommandFbs = 1;
  public static final byte CommandAckFbs = 2;
  public static final byte CancelOrderRequestFbs = 3;
  public static final byte ExchangeFbs = 4;
  public static final byte EventFbs = 5;
  public static final byte HeartbeatFbs = 6;
  public static final byte IssuerFbs = 7;
  public static final byte AggregateOrderBookUpdateFbs = 8;
  public static final byte NewOrderRequestFbs = 9;
  public static final byte OrderFbs = 10;
  public static final byte OrderRequestCompletionFbs = 11;
  public static final byte PositionFbs = 12;
  public static final byte RequestFbs = 13;
  public static final byte ResponseFbs = 14;
  public static final byte RiskControlFbs = 15;
  public static final byte RiskStateFbs = 16;
  public static final byte SecurityFbs = 17;
  public static final byte ServiceStatusFbs = 18;
  public static final byte StrategyTypeFbs = 19;
  public static final byte StrategyStatusFbs = 20;
  public static final byte StrategyParametersFbs = 21;
  public static final byte StrategyUndParametersFbs = 22;
  public static final byte StrategyIssuerParametersFbs = 23;
  public static final byte StrategyWrtParametersFbs = 24;
  public static final byte StrategySwitchFbs = 25;
  public static final byte TradeFbs = 26;
  public static final byte OrderBookSnapshotFbs = 27;
  public static final byte MarketStatsFbs = 28;
  public static final byte ScoreBoardSchemaFbs = 29;
  public static final byte ScoreBoardFbs = 30;
  public static final byte NoteFbs = 31;
  public static final byte ChartDataFbs = 32;
  public static final byte StrategyIssuerUndParametersFbs = 33;

  public static final String[] names = { "NONE", "CommandFbs", "CommandAckFbs", "CancelOrderRequestFbs", "ExchangeFbs", "EventFbs", "HeartbeatFbs", "IssuerFbs", "AggregateOrderBookUpdateFbs", "NewOrderRequestFbs", "OrderFbs", "OrderRequestCompletionFbs", "PositionFbs", "RequestFbs", "ResponseFbs", "RiskControlFbs", "RiskStateFbs", "SecurityFbs", "ServiceStatusFbs", "StrategyTypeFbs", "StrategyStatusFbs", "StrategyParametersFbs", "StrategyUndParametersFbs", "StrategyIssuerParametersFbs", "StrategyWrtParametersFbs", "StrategySwitchFbs", "TradeFbs", "OrderBookSnapshotFbs", "MarketStatsFbs", "ScoreBoardSchemaFbs", "ScoreBoardFbs", "NoteFbs", "ChartDataFbs", "StrategyIssuerUndParametersFbs", };

  public static String name(int e) { return names[e]; }
}

