// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MessageFbs extends Table {
  public static MessageFbs getRootAsMessageFbs(ByteBuffer _bb) { return getRootAsMessageFbs(_bb, new MessageFbs()); }
  public static MessageFbs getRootAsMessageFbs(ByteBuffer _bb, MessageFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MessageFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte messagePayloadType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table messagePayload(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createMessageFbs(FlatBufferBuilder builder,
      byte messagePayload_type,
      int messagePayloadOffset) {
    builder.startObject(2);
    MessageFbs.addMessagePayload(builder, messagePayloadOffset);
    MessageFbs.addMessagePayloadType(builder, messagePayload_type);
    return MessageFbs.endMessageFbs(builder);
  }

  public static void startMessageFbs(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addMessagePayloadType(FlatBufferBuilder builder, byte messagePayloadType) { builder.addByte(0, messagePayloadType, 0); }
  public static void addMessagePayload(FlatBufferBuilder builder, int messagePayloadOffset) { builder.addOffset(1, messagePayloadOffset, 0); }
  public static int endMessageFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishMessageFbsBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

