// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class NewOrderRequestFbs extends Table {
  public static NewOrderRequestFbs getRootAsNewOrderRequestFbs(ByteBuffer _bb) { return getRootAsNewOrderRequestFbs(_bb, new NewOrderRequestFbs()); }
  public static NewOrderRequestFbs getRootAsNewOrderRequestFbs(ByteBuffer _bb, NewOrderRequestFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public NewOrderRequestFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int clientKey() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long secSid() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public byte orderType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int quantity() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte side() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte tif() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public boolean isAlgoOrder() { int o = __offset(16); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int limitPrice() { int o = __offset(18); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int stopPrice() { int o = __offset(20); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long timeoutAt() { int o = __offset(22); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int portSid() { int o = __offset(24); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean retry() { int o = __offset(26); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createNewOrderRequestFbs(FlatBufferBuilder builder,
      int clientKey,
      long secSid,
      byte orderType,
      int quantity,
      byte side,
      byte tif,
      boolean isAlgoOrder,
      int limitPrice,
      int stopPrice,
      long timeoutAt,
      int portSid,
      boolean retry) {
    builder.startObject(12);
    NewOrderRequestFbs.addTimeoutAt(builder, timeoutAt);
    NewOrderRequestFbs.addSecSid(builder, secSid);
    NewOrderRequestFbs.addPortSid(builder, portSid);
    NewOrderRequestFbs.addStopPrice(builder, stopPrice);
    NewOrderRequestFbs.addLimitPrice(builder, limitPrice);
    NewOrderRequestFbs.addQuantity(builder, quantity);
    NewOrderRequestFbs.addClientKey(builder, clientKey);
    NewOrderRequestFbs.addRetry(builder, retry);
    NewOrderRequestFbs.addIsAlgoOrder(builder, isAlgoOrder);
    NewOrderRequestFbs.addTif(builder, tif);
    NewOrderRequestFbs.addSide(builder, side);
    NewOrderRequestFbs.addOrderType(builder, orderType);
    return NewOrderRequestFbs.endNewOrderRequestFbs(builder);
  }

  public static void startNewOrderRequestFbs(FlatBufferBuilder builder) { builder.startObject(12); }
  public static void addClientKey(FlatBufferBuilder builder, int clientKey) { builder.addInt(0, clientKey, 0); }
  public static void addSecSid(FlatBufferBuilder builder, long secSid) { builder.addLong(1, secSid, 0L); }
  public static void addOrderType(FlatBufferBuilder builder, byte orderType) { builder.addByte(2, orderType, 0); }
  public static void addQuantity(FlatBufferBuilder builder, int quantity) { builder.addInt(3, quantity, 0); }
  public static void addSide(FlatBufferBuilder builder, byte side) { builder.addByte(4, side, 0); }
  public static void addTif(FlatBufferBuilder builder, byte tif) { builder.addByte(5, tif, 0); }
  public static void addIsAlgoOrder(FlatBufferBuilder builder, boolean isAlgoOrder) { builder.addBoolean(6, isAlgoOrder, false); }
  public static void addLimitPrice(FlatBufferBuilder builder, int limitPrice) { builder.addInt(7, limitPrice, 0); }
  public static void addStopPrice(FlatBufferBuilder builder, int stopPrice) { builder.addInt(8, stopPrice, 0); }
  public static void addTimeoutAt(FlatBufferBuilder builder, long timeoutAt) { builder.addLong(9, timeoutAt, 0L); }
  public static void addPortSid(FlatBufferBuilder builder, int portSid) { builder.addInt(10, portSid, 0); }
  public static void addRetry(FlatBufferBuilder builder, boolean retry) { builder.addBoolean(11, retry, false); }
  public static int endNewOrderRequestFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

