// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class OptionStyleFbs {
  private OptionStyleFbs() { }
  public static final byte AMERICAN = 0;
  public static final byte EUROPEAN = 1;
  public static final byte ASIAN = 2;

  public static final String[] names = { "AMERICAN", "EUROPEAN", "ASIAN", };

  public static String name(int e) { return names[e]; }
}

