// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class OrderRequestRejectTypeFbs {
  private OrderRequestRejectTypeFbs() { }
  public static final byte TOO_LATE_TO_CANCEL = 0;
  public static final byte UNKNOWN_ORDER = 1;
  public static final byte ORDER_EXCEED_LIMIT_OR_ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS = 3;
  public static final byte DUPLICATE_ORDER_OR_DUPLICATE_CLIENT_ID_RECEIVED = 6;
  public static final byte INCORRECT_QTY = 13;
  public static final byte PRICE_EXCEEDS_CURRENT_PRICE_BAND = 16;
  public static final byte REFERENCE_PRICE_IS_NOT_AVAILABLE = 19;
  public static final byte NOTIONAL_VALUE_EXCEEDS_THRESHOLD = 20;
  public static final byte VALID_AND_NOT_REJECT = 80;
  public static final byte INSUFFICIENT_LONG_POSITION = 81;
  public static final byte CROSSED = 82;
  public static final byte INVALID_PRICE = 83;
  public static final byte ORDER_EXCEED_PURCHASING_POWER = 84;
  public static final byte RMS_INSUFFICIENT_LONG_POSITION_DIRECT_MAP = 93;
  public static final byte EXCEED_UNDERLYING_THROTTLE = 94;
  public static final byte TIMEOUT_BEFORE_THROTTLE = 95;
  public static final byte TIMEOUT_AFTER_THROTTLED = 96;
  public static final byte TIMEOUT = 97;
  public static final byte THROTTLED = 98;
  public static final byte OTHER = 99;
  public static final byte PRICE_EXCEEDS_CURRENT_PRICE_BAND_OVERRIDE_NOT_ALLOWED = 101;
  public static final byte PRICE_EXCEEDS_CURRENT_PRICE_BAND_OTHER = 102;

  public static final String[] names = { "TOO_LATE_TO_CANCEL", "UNKNOWN_ORDER", "", "ORDER_EXCEED_LIMIT_OR_ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS", "", "", "DUPLICATE_ORDER_OR_DUPLICATE_CLIENT_ID_RECEIVED", "", "", "", "", "", "", "INCORRECT_QTY", "", "", "PRICE_EXCEEDS_CURRENT_PRICE_BAND", "", "", "REFERENCE_PRICE_IS_NOT_AVAILABLE", "NOTIONAL_VALUE_EXCEEDS_THRESHOLD", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "VALID_AND_NOT_REJECT", "INSUFFICIENT_LONG_POSITION", "CROSSED", "INVALID_PRICE", "ORDER_EXCEED_PURCHASING_POWER", "", "", "", "", "", "", "", "", "RMS_INSUFFICIENT_LONG_POSITION_DIRECT_MAP", "EXCEED_UNDERLYING_THROTTLE", "TIMEOUT_BEFORE_THROTTLE", "TIMEOUT_AFTER_THROTTLED", "TIMEOUT", "THROTTLED", "OTHER", "", "PRICE_EXCEEDS_CURRENT_PRICE_BAND_OVERRIDE_NOT_ALLOWED", "PRICE_EXCEEDS_CURRENT_PRICE_BAND_OTHER", };

  public static String name(int e) { return names[e]; }
}

