// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class OrderRequestCompletionFbs extends Table {
  public static OrderRequestCompletionFbs getRootAsOrderRequestCompletionFbs(ByteBuffer _bb) { return getRootAsOrderRequestCompletionFbs(_bb, new OrderRequestCompletionFbs()); }
  public static OrderRequestCompletionFbs getRootAsOrderRequestCompletionFbs(ByteBuffer _bb, OrderRequestCompletionFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public OrderRequestCompletionFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int clientKey() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int orderSid() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte completionType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte rejectType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String reason() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reasonAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }

  public static int createOrderRequestCompletionFbs(FlatBufferBuilder builder,
      int clientKey,
      int orderSid,
      byte completionType,
      byte rejectType,
      int reasonOffset) {
    builder.startObject(5);
    OrderRequestCompletionFbs.addReason(builder, reasonOffset);
    OrderRequestCompletionFbs.addOrderSid(builder, orderSid);
    OrderRequestCompletionFbs.addClientKey(builder, clientKey);
    OrderRequestCompletionFbs.addRejectType(builder, rejectType);
    OrderRequestCompletionFbs.addCompletionType(builder, completionType);
    return OrderRequestCompletionFbs.endOrderRequestCompletionFbs(builder);
  }

  public static void startOrderRequestCompletionFbs(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addClientKey(FlatBufferBuilder builder, int clientKey) { builder.addInt(0, clientKey, 0); }
  public static void addOrderSid(FlatBufferBuilder builder, int orderSid) { builder.addInt(1, orderSid, 0); }
  public static void addCompletionType(FlatBufferBuilder builder, byte completionType) { builder.addByte(2, completionType, 0); }
  public static void addRejectType(FlatBufferBuilder builder, byte rejectType) { builder.addByte(3, rejectType, 0); }
  public static void addReason(FlatBufferBuilder builder, int reasonOffset) { builder.addOffset(4, reasonOffset, 0); }
  public static int endOrderRequestCompletionFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

