// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class OrderBookSnapshotEntryFbs extends Table {
  public static OrderBookSnapshotEntryFbs getRootAsOrderBookSnapshotEntryFbs(ByteBuffer _bb) { return getRootAsOrderBookSnapshotEntryFbs(_bb, new OrderBookSnapshotEntryFbs()); }
  public static OrderBookSnapshotEntryFbs getRootAsOrderBookSnapshotEntryFbs(ByteBuffer _bb, OrderBookSnapshotEntryFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public OrderBookSnapshotEntryFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int price() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int quantity() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int tickLevel() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createOrderBookSnapshotEntryFbs(FlatBufferBuilder builder,
      int price,
      int quantity,
      int tickLevel) {
    builder.startObject(3);
    OrderBookSnapshotEntryFbs.addTickLevel(builder, tickLevel);
    OrderBookSnapshotEntryFbs.addQuantity(builder, quantity);
    OrderBookSnapshotEntryFbs.addPrice(builder, price);
    return OrderBookSnapshotEntryFbs.endOrderBookSnapshotEntryFbs(builder);
  }

  public static void startOrderBookSnapshotEntryFbs(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addPrice(FlatBufferBuilder builder, int price) { builder.addInt(0, price, 0); }
  public static void addQuantity(FlatBufferBuilder builder, int quantity) { builder.addInt(1, quantity, 0); }
  public static void addTickLevel(FlatBufferBuilder builder, int tickLevel) { builder.addInt(2, tickLevel, 0); }
  public static int endOrderBookSnapshotEntryFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

