// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class OrderRejectTypeFbs {
  private OrderRejectTypeFbs() { }
  public static final byte INVALID = 0;
  public static final byte ORDER_EXCEED_LIMIT = 3;
  public static final byte DUPLICATE_ORDER = 6;
  public static final byte INCORRECT_QTY = 13;
  public static final byte PRICE_EXCEEDS_CURRENT_PRICE_BAND = 16;
  public static final byte REFERENCE_PRICE_IS_NOT_AVAILABLE = 19;
  public static final byte NOTIONAL_VALUE_EXCEEDS_THRESHOLD = 20;
  public static final byte VALID_AND_NOT_REJECT = 80;
  public static final byte INSUFFICIENT_LONG_POSITION = 81;
  public static final byte CROSSED = 82;
  public static final byte INVALID_PRICE = 83;
  public static final byte ORDER_EXCEED_PURCHASING_POWER = 84;
  public static final byte RMS_INSUFFICIENT_LONG_POSITION_DIRECT_MAP = 93;
  public static final byte OTHER_INTERNALLY = 98;
  public static final byte OTHER = 99;
  public static final byte PRICE_EXCEEDS_CURRENT_PRICE_BAND_OVERRIDE_NOT_ALLOWED = 101;
  public static final byte PRICE_EXCEEDS_CURRENT_PRICE_BAND_OTHER = 102;
}

