// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class OrderRequestAcceptedFbs extends Table {
  public static OrderRequestAcceptedFbs getRootAsOrderRequestAcceptedFbs(ByteBuffer _bb) { return getRootAsOrderRequestAcceptedFbs(_bb, new OrderRequestAcceptedFbs()); }
  public static OrderRequestAcceptedFbs getRootAsOrderRequestAcceptedFbs(ByteBuffer _bb, OrderRequestAcceptedFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public OrderRequestAcceptedFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int clientKey() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int orderSid() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createOrderRequestAcceptedFbs(FlatBufferBuilder builder,
      int clientKey,
      int orderSid) {
    builder.startObject(2);
    OrderRequestAcceptedFbs.addOrderSid(builder, orderSid);
    OrderRequestAcceptedFbs.addClientKey(builder, clientKey);
    return OrderRequestAcceptedFbs.endOrderRequestAcceptedFbs(builder);
  }

  public static void startOrderRequestAcceptedFbs(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addClientKey(FlatBufferBuilder builder, int clientKey) { builder.addInt(0, clientKey, 0); }
  public static void addOrderSid(FlatBufferBuilder builder, int orderSid) { builder.addInt(1, orderSid, 0); }
  public static int endOrderRequestAcceptedFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

