// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class OrderTypeFbs {
  private OrderTypeFbs() { }
  public static final byte INVALID = 0;
  public static final byte MARKET_ORDER = 49;
  public static final byte LIMIT_ORDER = 50;
  public static final byte STOP_ORDER = 51;
  public static final byte STOP_LIMIT_ORDER = 52;
  public static final byte ENHANCED_LIMIT_ORDER = 53;
  public static final byte MARKET_LIMIT_ORDER = 75;
  public static final byte LIMIT_THEN_CANCEL_ORDER = 88;
}

