// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class OrderBookSnapshotFbs extends Table {
  public static OrderBookSnapshotFbs getRootAsOrderBookSnapshotFbs(ByteBuffer _bb) { return getRootAsOrderBookSnapshotFbs(_bb, new OrderBookSnapshotFbs()); }
  public static OrderBookSnapshotFbs getRootAsOrderBookSnapshotFbs(ByteBuffer _bb, OrderBookSnapshotFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public OrderBookSnapshotFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long secSid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int seqNum() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long transactTime() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public OrderBookSnapshotEntryFbs bidDepth(int j) { return bidDepth(new OrderBookSnapshotEntryFbs(), j); }
  public OrderBookSnapshotEntryFbs bidDepth(OrderBookSnapshotEntryFbs obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int bidDepthLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public OrderBookSnapshotEntryFbs askDepth(int j) { return askDepth(new OrderBookSnapshotEntryFbs(), j); }
  public OrderBookSnapshotEntryFbs askDepth(OrderBookSnapshotEntryFbs obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int askDepthLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }

  public static int createOrderBookSnapshotFbs(FlatBufferBuilder builder,
      long secSid,
      int seqNum,
      long transactTime,
      int bidDepthOffset,
      int askDepthOffset) {
    builder.startObject(5);
    OrderBookSnapshotFbs.addTransactTime(builder, transactTime);
    OrderBookSnapshotFbs.addSecSid(builder, secSid);
    OrderBookSnapshotFbs.addAskDepth(builder, askDepthOffset);
    OrderBookSnapshotFbs.addBidDepth(builder, bidDepthOffset);
    OrderBookSnapshotFbs.addSeqNum(builder, seqNum);
    return OrderBookSnapshotFbs.endOrderBookSnapshotFbs(builder);
  }

  public static void startOrderBookSnapshotFbs(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addSecSid(FlatBufferBuilder builder, long secSid) { builder.addLong(0, secSid, 0L); }
  public static void addSeqNum(FlatBufferBuilder builder, int seqNum) { builder.addInt(1, seqNum, 0); }
  public static void addTransactTime(FlatBufferBuilder builder, long transactTime) { builder.addLong(2, transactTime, 0L); }
  public static void addBidDepth(FlatBufferBuilder builder, int bidDepthOffset) { builder.addOffset(3, bidDepthOffset, 0); }
  public static int createBidDepthVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startBidDepthVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAskDepth(FlatBufferBuilder builder, int askDepthOffset) { builder.addOffset(4, askDepthOffset, 0); }
  public static int createAskDepthVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAskDepthVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endOrderBookSnapshotFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

