// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class OrderRequestCompletionTypeFbs {
  private OrderRequestCompletionTypeFbs() { }
  public static final byte OK = 0;
  public static final byte FAILED = 1;
  public static final byte REJECTED_INTERNALLY = 2;
  public static final byte ALREADY_IN_PENDING_CANCEL = 3;
  public static final byte ALREADY_IN_PENDING_AMEND = 4;
  public static final byte REJECTED = 5;

  public static final String[] names = { "OK", "FAILED", "REJECTED_INTERNALLY", "ALREADY_IN_PENDING_CANCEL", "ALREADY_IN_PENDING_AMEND", "REJECTED", };

  public static String name(int e) { return names[e]; }
}

