// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class OrderStatusFbs {
  private OrderStatusFbs() { }
  public static final byte PENDING_NEW = 0;
  public static final byte NEW = 1;
  public static final byte PENDING_AMEND = 2;
  public static final byte FILLED = 3;
  public static final byte PENDING_CANCEL = 4;
  public static final byte CANCELLED = 5;
  public static final byte EXPIRED = 6;
  public static final byte REJECTED = 7;
  public static final byte FAILED = 8;
  public static final byte PARTIALLY_FILLED = 9;

  public static final String[] names = { "PENDING_NEW", "NEW", "PENDING_AMEND", "FILLED", "PENDING_CANCEL", "CANCELLED", "EXPIRED", "REJECTED", "FAILED", "PARTIALLY_FILLED", };

  public static String name(int e) { return names[e]; }
}

