// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class ParameterTypeFbs {
  private ParameterTypeFbs() { }
  public static final byte NULL_VAL = -128;
  public static final byte BOUND = 0;
  public static final byte BROADCAST_FREQ = 1;
  public static final byte ENTITY_TYPE = 2;
  public static final byte EXCHANGE_CODE = 3;
  public static final byte EXCHANGE_SID = 4;
  public static final byte SECURITY_SID = 5;
  public static final byte ORIGIN = 6;
  public static final byte OPTION_TYPE = 7;
  public static final byte RIC = 8;
  public static final byte STRATEGY_ID = 9;
  public static final byte SECURITY_CODE = 10;
  public static final byte SECURITY_TYPE = 11;
  public static final byte UNDERLYING_SECURITY_SID = 12;
  public static final byte UNDERLYING_SECURITY_CODE = 13;
  public static final byte WAIT_IN_MS = 14;
  public static final byte SERVICE_TYPE = 15;
  public static final byte ECHO_REMAINING = 16;
  public static final byte MESSAGE_TYPE = 17;
  public static final byte SINK_ID = 18;
  public static final byte DATA_TYPE = 19;
  public static final byte DUMMY_EXCHANGE_ACTION_TYPE = 20;
  public static final byte PARAM_NAME = 21;
  public static final byte PARAM_VALUE = 22;
  public static final byte PURCHASING_POWER = 23;
  public static final byte CHANNEL_ID = 24;
  public static final byte PORTFOLIO_SID = 25;
  public static final byte ISSUER_SID = 26;
  public static final byte CHANNEL_SEQ = 27;
  public static final byte ENTITY_SID = 28;
  public static final byte DESCRIPTION = 29;
  public static final byte IS_DELETED = 30;
  public static final byte IS_ARCHIVED = 31;
  public static final byte NOTE_SID = 32;
  public static final byte WINDOW_SIZE_IN_SEC = 33;
  public static final byte SIDE = 34;
  public static final byte QUANTITY = 35;
  public static final byte PRICE = 36;
  public static final byte FROM_TIME = 37;
  public static final byte TO_TIME = 38;
  public static final byte STRATEGY_SWITCH_TYPE = 39;
  public static final byte CLIENT_ORDER_ID = 40;

  public static final String[] names = { "NULL_VAL", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "BOUND", "BROADCAST_FREQ", "ENTITY_TYPE", "EXCHANGE_CODE", "EXCHANGE_SID", "SECURITY_SID", "ORIGIN", "OPTION_TYPE", "RIC", "STRATEGY_ID", "SECURITY_CODE", "SECURITY_TYPE", "UNDERLYING_SECURITY_SID", "UNDERLYING_SECURITY_CODE", "WAIT_IN_MS", "SERVICE_TYPE", "ECHO_REMAINING", "MESSAGE_TYPE", "SINK_ID", "DATA_TYPE", "DUMMY_EXCHANGE_ACTION_TYPE", "PARAM_NAME", "PARAM_VALUE", "PURCHASING_POWER", "CHANNEL_ID", "PORTFOLIO_SID", "ISSUER_SID", "CHANNEL_SEQ", "ENTITY_SID", "DESCRIPTION", "IS_DELETED", "IS_ARCHIVED", "NOTE_SID", "WINDOW_SIZE_IN_SEC", "SIDE", "QUANTITY", "PRICE", "FROM_TIME", "TO_TIME", "STRATEGY_SWITCH_TYPE", "CLIENT_ORDER_ID", };

  public static String name(int e) { return names[e - NULL_VAL]; }
}

