// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PositionFbs extends Table {
  public static PositionFbs getRootAsPositionFbs(ByteBuffer _bb) { return getRootAsPositionFbs(_bb, new PositionFbs()); }
  public static PositionFbs getRootAsPositionFbs(ByteBuffer _bb, PositionFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public PositionFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long entitySid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public byte entityType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long openPosition() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long openCallPosition() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long openPutPosition() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long buyQty() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public double buyNotional() { int o = __offset(16); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public long sellQty() { int o = __offset(18); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public double sellNotional() { int o = __offset(20); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public long osBuyQty() { int o = __offset(22); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public double osBuyNotional() { int o = __offset(24); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public long osSellQty() { int o = __offset(26); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public double osSellNotional() { int o = __offset(28); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double capUsed() { int o = __offset(30); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double maxCapUsed() { int o = __offset(32); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double fees() { int o = __offset(34); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double commission() { int o = __offset(36); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double netRealizedPnl() { int o = __offset(38); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double unrealizedPnl() { int o = __offset(40); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double avgBuyPrice() { int o = __offset(42); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double avgSellPrice() { int o = __offset(44); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double mtmBuyPrice() { int o = __offset(46); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double mtmSellPrice() { int o = __offset(48); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double totalPnl() { int o = __offset(50); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public int tradeCount() { int o = __offset(52); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public double experimentalNetRealizedPnl() { int o = __offset(54); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double experimentalUnrealizedPnl() { int o = __offset(56); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double experimentalTotalPnl() { int o = __offset(58); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createPositionFbs(FlatBufferBuilder builder,
      long entitySid,
      byte entityType,
      long openPosition,
      long openCallPosition,
      long openPutPosition,
      long buyQty,
      double buyNotional,
      long sellQty,
      double sellNotional,
      long osBuyQty,
      double osBuyNotional,
      long osSellQty,
      double osSellNotional,
      double capUsed,
      double maxCapUsed,
      double fees,
      double commission,
      double netRealizedPnl,
      double unrealizedPnl,
      double avgBuyPrice,
      double avgSellPrice,
      double mtmBuyPrice,
      double mtmSellPrice,
      double totalPnl,
      int tradeCount,
      double experimentalNetRealizedPnl,
      double experimentalUnrealizedPnl,
      double experimentalTotalPnl) {
    builder.startObject(28);
    PositionFbs.addExperimentalTotalPnl(builder, experimentalTotalPnl);
    PositionFbs.addExperimentalUnrealizedPnl(builder, experimentalUnrealizedPnl);
    PositionFbs.addExperimentalNetRealizedPnl(builder, experimentalNetRealizedPnl);
    PositionFbs.addTotalPnl(builder, totalPnl);
    PositionFbs.addMtmSellPrice(builder, mtmSellPrice);
    PositionFbs.addMtmBuyPrice(builder, mtmBuyPrice);
    PositionFbs.addAvgSellPrice(builder, avgSellPrice);
    PositionFbs.addAvgBuyPrice(builder, avgBuyPrice);
    PositionFbs.addUnrealizedPnl(builder, unrealizedPnl);
    PositionFbs.addNetRealizedPnl(builder, netRealizedPnl);
    PositionFbs.addCommission(builder, commission);
    PositionFbs.addFees(builder, fees);
    PositionFbs.addMaxCapUsed(builder, maxCapUsed);
    PositionFbs.addCapUsed(builder, capUsed);
    PositionFbs.addOsSellNotional(builder, osSellNotional);
    PositionFbs.addOsSellQty(builder, osSellQty);
    PositionFbs.addOsBuyNotional(builder, osBuyNotional);
    PositionFbs.addOsBuyQty(builder, osBuyQty);
    PositionFbs.addSellNotional(builder, sellNotional);
    PositionFbs.addSellQty(builder, sellQty);
    PositionFbs.addBuyNotional(builder, buyNotional);
    PositionFbs.addBuyQty(builder, buyQty);
    PositionFbs.addOpenPutPosition(builder, openPutPosition);
    PositionFbs.addOpenCallPosition(builder, openCallPosition);
    PositionFbs.addOpenPosition(builder, openPosition);
    PositionFbs.addEntitySid(builder, entitySid);
    PositionFbs.addTradeCount(builder, tradeCount);
    PositionFbs.addEntityType(builder, entityType);
    return PositionFbs.endPositionFbs(builder);
  }

  public static void startPositionFbs(FlatBufferBuilder builder) { builder.startObject(28); }
  public static void addEntitySid(FlatBufferBuilder builder, long entitySid) { builder.addLong(0, entitySid, 0L); }
  public static void addEntityType(FlatBufferBuilder builder, byte entityType) { builder.addByte(1, entityType, 0); }
  public static void addOpenPosition(FlatBufferBuilder builder, long openPosition) { builder.addLong(2, openPosition, 0L); }
  public static void addOpenCallPosition(FlatBufferBuilder builder, long openCallPosition) { builder.addLong(3, openCallPosition, 0L); }
  public static void addOpenPutPosition(FlatBufferBuilder builder, long openPutPosition) { builder.addLong(4, openPutPosition, 0L); }
  public static void addBuyQty(FlatBufferBuilder builder, long buyQty) { builder.addLong(5, buyQty, 0L); }
  public static void addBuyNotional(FlatBufferBuilder builder, double buyNotional) { builder.addDouble(6, buyNotional, 0.0); }
  public static void addSellQty(FlatBufferBuilder builder, long sellQty) { builder.addLong(7, sellQty, 0L); }
  public static void addSellNotional(FlatBufferBuilder builder, double sellNotional) { builder.addDouble(8, sellNotional, 0.0); }
  public static void addOsBuyQty(FlatBufferBuilder builder, long osBuyQty) { builder.addLong(9, osBuyQty, 0L); }
  public static void addOsBuyNotional(FlatBufferBuilder builder, double osBuyNotional) { builder.addDouble(10, osBuyNotional, 0.0); }
  public static void addOsSellQty(FlatBufferBuilder builder, long osSellQty) { builder.addLong(11, osSellQty, 0L); }
  public static void addOsSellNotional(FlatBufferBuilder builder, double osSellNotional) { builder.addDouble(12, osSellNotional, 0.0); }
  public static void addCapUsed(FlatBufferBuilder builder, double capUsed) { builder.addDouble(13, capUsed, 0.0); }
  public static void addMaxCapUsed(FlatBufferBuilder builder, double maxCapUsed) { builder.addDouble(14, maxCapUsed, 0.0); }
  public static void addFees(FlatBufferBuilder builder, double fees) { builder.addDouble(15, fees, 0.0); }
  public static void addCommission(FlatBufferBuilder builder, double commission) { builder.addDouble(16, commission, 0.0); }
  public static void addNetRealizedPnl(FlatBufferBuilder builder, double netRealizedPnl) { builder.addDouble(17, netRealizedPnl, 0.0); }
  public static void addUnrealizedPnl(FlatBufferBuilder builder, double unrealizedPnl) { builder.addDouble(18, unrealizedPnl, 0.0); }
  public static void addAvgBuyPrice(FlatBufferBuilder builder, double avgBuyPrice) { builder.addDouble(19, avgBuyPrice, 0.0); }
  public static void addAvgSellPrice(FlatBufferBuilder builder, double avgSellPrice) { builder.addDouble(20, avgSellPrice, 0.0); }
  public static void addMtmBuyPrice(FlatBufferBuilder builder, double mtmBuyPrice) { builder.addDouble(21, mtmBuyPrice, 0.0); }
  public static void addMtmSellPrice(FlatBufferBuilder builder, double mtmSellPrice) { builder.addDouble(22, mtmSellPrice, 0.0); }
  public static void addTotalPnl(FlatBufferBuilder builder, double totalPnl) { builder.addDouble(23, totalPnl, 0.0); }
  public static void addTradeCount(FlatBufferBuilder builder, int tradeCount) { builder.addInt(24, tradeCount, 0); }
  public static void addExperimentalNetRealizedPnl(FlatBufferBuilder builder, double experimentalNetRealizedPnl) { builder.addDouble(25, experimentalNetRealizedPnl, 0.0); }
  public static void addExperimentalUnrealizedPnl(FlatBufferBuilder builder, double experimentalUnrealizedPnl) { builder.addDouble(26, experimentalUnrealizedPnl, 0.0); }
  public static void addExperimentalTotalPnl(FlatBufferBuilder builder, double experimentalTotalPnl) { builder.addDouble(27, experimentalTotalPnl, 0.0); }
  public static int endPositionFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

