// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class PricingMode {
  private PricingMode() { }
  public static final byte NULL = -128;
  public static final byte UNKNOWN = 1;
  public static final byte MID = 2;
  public static final byte WEIGHTED = 3;
  public static final byte ADJUSTVOL = 4;
}

