// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class PutOrCallFbs {
  private PutOrCallFbs() { }
  public static final byte PUT = 0;
  public static final byte CALL = 1;

  public static final String[] names = { "PUT", "CALL", };

  public static String name(int e) { return names[e]; }
}

