// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RequestFbs extends Table {
  public static RequestFbs getRootAsRequestFbs(ByteBuffer _bb) { return getRootAsRequestFbs(_bb, new RequestFbs()); }
  public static RequestFbs getRootAsRequestFbs(ByteBuffer _bb, RequestFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RequestFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int clientKey() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean toSend() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public byte requestType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public ParameterFbs parameters(int j) { return parameters(new ParameterFbs(), j); }
  public ParameterFbs parameters(ParameterFbs obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int parametersLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }

  public static int createRequestFbs(FlatBufferBuilder builder,
      int clientKey,
      boolean toSend,
      byte requestType,
      int parametersOffset) {
    builder.startObject(4);
    RequestFbs.addParameters(builder, parametersOffset);
    RequestFbs.addClientKey(builder, clientKey);
    RequestFbs.addRequestType(builder, requestType);
    RequestFbs.addToSend(builder, toSend);
    return RequestFbs.endRequestFbs(builder);
  }

  public static void startRequestFbs(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addClientKey(FlatBufferBuilder builder, int clientKey) { builder.addInt(0, clientKey, 0); }
  public static void addToSend(FlatBufferBuilder builder, boolean toSend) { builder.addBoolean(1, toSend, false); }
  public static void addRequestType(FlatBufferBuilder builder, byte requestType) { builder.addByte(2, requestType, 0); }
  public static void addParameters(FlatBufferBuilder builder, int parametersOffset) { builder.addOffset(3, parametersOffset, 0); }
  public static int createParametersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startParametersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRequestFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

