// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class RequestTypeFbs {
  private RequestTypeFbs() { }
  public static final byte CREATE = 0;
  public static final byte GET = 1;
  public static final byte INIT = 2;
  public static final byte START = 4;
  public static final byte STOP = 5;
  public static final byte SUBSCRIBE = 6;
  public static final byte UNSUBSCRIBE = 7;
  public static final byte REGISTER = 8;
  public static final byte UNREGISTER = 9;
  public static final byte ECHO = 10;
  public static final byte GET_PERF_STAT = 11;
  public static final byte GET_SYSTEM_STATUS = 12;
  public static final byte UPDATE = 13;
  public static final byte GET_AND_SUBSCRIBE = 14;

  public static final String[] names = { "CREATE", "GET", "INIT", "", "START", "STOP", "SUBSCRIBE", "UNSUBSCRIBE", "REGISTER", "UNREGISTER", "ECHO", "GET_PERF_STAT", "GET_SYSTEM_STATUS", "UPDATE", "GET_AND_SUBSCRIBE", };

  public static String name(int e) { return names[e]; }
}

