// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ResponseFbs extends Table {
  public static ResponseFbs getRootAsResponseFbs(ByteBuffer _bb) { return getRootAsResponseFbs(_bb, new ResponseFbs()); }
  public static ResponseFbs getRootAsResponseFbs(ByteBuffer _bb, ResponseFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ResponseFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int clientKey() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean isLast() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public byte resultType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte messagePayloadType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table messagePayload(Table obj) { int o = __offset(12); return o != 0 ? __union(obj, o) : null; }

  public static int createResponseFbs(FlatBufferBuilder builder,
      int clientKey,
      boolean isLast,
      byte resultType,
      byte messagePayload_type,
      int messagePayloadOffset) {
    builder.startObject(5);
    ResponseFbs.addMessagePayload(builder, messagePayloadOffset);
    ResponseFbs.addClientKey(builder, clientKey);
    ResponseFbs.addMessagePayloadType(builder, messagePayload_type);
    ResponseFbs.addResultType(builder, resultType);
    ResponseFbs.addIsLast(builder, isLast);
    return ResponseFbs.endResponseFbs(builder);
  }

  public static void startResponseFbs(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addClientKey(FlatBufferBuilder builder, int clientKey) { builder.addInt(0, clientKey, 0); }
  public static void addIsLast(FlatBufferBuilder builder, boolean isLast) { builder.addBoolean(1, isLast, false); }
  public static void addResultType(FlatBufferBuilder builder, byte resultType) { builder.addByte(2, resultType, 0); }
  public static void addMessagePayloadType(FlatBufferBuilder builder, byte messagePayloadType) { builder.addByte(3, messagePayloadType, 0); }
  public static void addMessagePayload(FlatBufferBuilder builder, int messagePayloadOffset) { builder.addOffset(4, messagePayloadOffset, 0); }
  public static int endResponseFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

