// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class ResultTypeFbs {
  private ResultTypeFbs() { }
  public static final byte OK = 0;
  public static final byte FAILED = 1;

  public static final String[] names = { "OK", "FAILED", };

  public static String name(int e) { return names[e]; }
}

