// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RiskStateFbs extends Table {
  public static RiskStateFbs getRootAsRiskStateFbs(ByteBuffer _bb) { return getRootAsRiskStateFbs(_bb, new RiskStateFbs()); }
  public static RiskStateFbs getRootAsRiskStateFbs(ByteBuffer _bb, RiskStateFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RiskStateFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte entityType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long entitySid() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public RiskStateDetailsFbs details(int j) { return details(new RiskStateDetailsFbs(), j); }
  public RiskStateDetailsFbs details(RiskStateDetailsFbs obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int detailsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }

  public static int createRiskStateFbs(FlatBufferBuilder builder,
      byte entityType,
      long entitySid,
      int detailsOffset) {
    builder.startObject(3);
    RiskStateFbs.addEntitySid(builder, entitySid);
    RiskStateFbs.addDetails(builder, detailsOffset);
    RiskStateFbs.addEntityType(builder, entityType);
    return RiskStateFbs.endRiskStateFbs(builder);
  }

  public static void startRiskStateFbs(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addEntityType(FlatBufferBuilder builder, byte entityType) { builder.addByte(0, entityType, 0); }
  public static void addEntitySid(FlatBufferBuilder builder, long entitySid) { builder.addLong(1, entitySid, 0L); }
  public static void addDetails(FlatBufferBuilder builder, int detailsOffset) { builder.addOffset(2, detailsOffset, 0); }
  public static int createDetailsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDetailsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRiskStateFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

