// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RiskControlFbs extends Table {
  public static RiskControlFbs getRootAsRiskControlFbs(ByteBuffer _bb) { return getRootAsRiskControlFbs(_bb, new RiskControlFbs()); }
  public static RiskControlFbs getRootAsRiskControlFbs(ByteBuffer _bb, RiskControlFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RiskControlFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte entityType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public boolean toAllEntity() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public long specificEntitySid() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public RiskControlSettingFbs settings(int j) { return settings(new RiskControlSettingFbs(), j); }
  public RiskControlSettingFbs settings(RiskControlSettingFbs obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int settingsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }

  public static int createRiskControlFbs(FlatBufferBuilder builder,
      byte entityType,
      boolean toAllEntity,
      long specificEntitySid,
      int settingsOffset) {
    builder.startObject(4);
    RiskControlFbs.addSpecificEntitySid(builder, specificEntitySid);
    RiskControlFbs.addSettings(builder, settingsOffset);
    RiskControlFbs.addToAllEntity(builder, toAllEntity);
    RiskControlFbs.addEntityType(builder, entityType);
    return RiskControlFbs.endRiskControlFbs(builder);
  }

  public static void startRiskControlFbs(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addEntityType(FlatBufferBuilder builder, byte entityType) { builder.addByte(0, entityType, 0); }
  public static void addToAllEntity(FlatBufferBuilder builder, boolean toAllEntity) { builder.addBoolean(1, toAllEntity, false); }
  public static void addSpecificEntitySid(FlatBufferBuilder builder, long specificEntitySid) { builder.addLong(2, specificEntitySid, 0L); }
  public static void addSettings(FlatBufferBuilder builder, int settingsOffset) { builder.addOffset(3, settingsOffset, 0); }
  public static int createSettingsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSettingsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRiskControlFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

