// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class RiskControlTypeFbs {
  private RiskControlTypeFbs() { }
  public static final byte INVALID = 0;
  public static final byte MAX_PROFIT = 1;
  public static final byte MAX_LOSS = 2;
  public static final byte MAX_OPEN_POSITION = 3;
  public static final byte MAX_CAP_LIMIT = 4;

  public static final String[] names = { "INVALID", "MAX_PROFIT", "MAX_LOSS", "MAX_OPEN_POSITION", "MAX_CAP_LIMIT", };

  public static String name(int e) { return names[e]; }
}

