// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RiskStateDetailsFbs extends Table {
  public static RiskStateDetailsFbs getRootAsRiskStateDetailsFbs(ByteBuffer _bb) { return getRootAsRiskStateDetailsFbs(_bb, new RiskStateDetailsFbs()); }
  public static RiskStateDetailsFbs getRootAsRiskStateDetailsFbs(ByteBuffer _bb, RiskStateDetailsFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RiskStateDetailsFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public double current() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double previous() { int o = __offset(8); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public boolean exceeded() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createRiskStateDetailsFbs(FlatBufferBuilder builder,
      byte type,
      double current,
      double previous,
      boolean exceeded) {
    builder.startObject(4);
    RiskStateDetailsFbs.addPrevious(builder, previous);
    RiskStateDetailsFbs.addCurrent(builder, current);
    RiskStateDetailsFbs.addExceeded(builder, exceeded);
    RiskStateDetailsFbs.addType(builder, type);
    return RiskStateDetailsFbs.endRiskStateDetailsFbs(builder);
  }

  public static void startRiskStateDetailsFbs(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addCurrent(FlatBufferBuilder builder, double current) { builder.addDouble(1, current, 0.0); }
  public static void addPrevious(FlatBufferBuilder builder, double previous) { builder.addDouble(2, previous, 0.0); }
  public static void addExceeded(FlatBufferBuilder builder, boolean exceeded) { builder.addBoolean(3, exceeded, false); }
  public static int endRiskStateDetailsFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

