// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RiskControlSettingFbs extends Table {
  public static RiskControlSettingFbs getRootAsRiskControlSettingFbs(ByteBuffer _bb) { return getRootAsRiskControlSettingFbs(_bb, new RiskControlSettingFbs()); }
  public static RiskControlSettingFbs getRootAsRiskControlSettingFbs(ByteBuffer _bb, RiskControlSettingFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RiskControlSettingFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public double value() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createRiskControlSettingFbs(FlatBufferBuilder builder,
      byte type,
      double value) {
    builder.startObject(2);
    RiskControlSettingFbs.addValue(builder, value);
    RiskControlSettingFbs.addType(builder, type);
    return RiskControlSettingFbs.endRiskControlSettingFbs(builder);
  }

  public static void startRiskControlSettingFbs(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addValue(FlatBufferBuilder builder, double value) { builder.addDouble(1, value, 0.0); }
  public static int endRiskControlSettingFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

