// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ScoreBoardDetailFbs extends Table {
  public static ScoreBoardDetailFbs getRootAsScoreBoardDetailFbs(ByteBuffer _bb) { return getRootAsScoreBoardDetailFbs(_bb, new ScoreBoardDetailFbs()); }
  public static ScoreBoardDetailFbs getRootAsScoreBoardDetailFbs(ByteBuffer _bb, ScoreBoardDetailFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ScoreBoardDetailFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int fieldId() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long fieldValueLong() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createScoreBoardDetailFbs(FlatBufferBuilder builder,
      int fieldId,
      long fieldValueLong) {
    builder.startObject(2);
    ScoreBoardDetailFbs.addFieldValueLong(builder, fieldValueLong);
    ScoreBoardDetailFbs.addFieldId(builder, fieldId);
    return ScoreBoardDetailFbs.endScoreBoardDetailFbs(builder);
  }

  public static void startScoreBoardDetailFbs(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addFieldId(FlatBufferBuilder builder, int fieldId) { builder.addInt(0, fieldId, 0); }
  public static void addFieldValueLong(FlatBufferBuilder builder, long fieldValueLong) { builder.addLong(1, fieldValueLong, 0L); }
  public static int endScoreBoardDetailFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

