// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ScoreBoardSchemaFieldFbs extends Table {
  public static ScoreBoardSchemaFieldFbs getRootAsScoreBoardSchemaFieldFbs(ByteBuffer _bb) { return getRootAsScoreBoardSchemaFieldFbs(_bb, new ScoreBoardSchemaFieldFbs()); }
  public static ScoreBoardSchemaFieldFbs getRootAsScoreBoardSchemaFieldFbs(ByteBuffer _bb, ScoreBoardSchemaFieldFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ScoreBoardSchemaFieldFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int fieldId() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String fieldName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fieldNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public byte fieldType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createScoreBoardSchemaFieldFbs(FlatBufferBuilder builder,
      int fieldId,
      int fieldNameOffset,
      byte fieldType) {
    builder.startObject(3);
    ScoreBoardSchemaFieldFbs.addFieldName(builder, fieldNameOffset);
    ScoreBoardSchemaFieldFbs.addFieldId(builder, fieldId);
    ScoreBoardSchemaFieldFbs.addFieldType(builder, fieldType);
    return ScoreBoardSchemaFieldFbs.endScoreBoardSchemaFieldFbs(builder);
  }

  public static void startScoreBoardSchemaFieldFbs(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addFieldId(FlatBufferBuilder builder, int fieldId) { builder.addInt(0, fieldId, 0); }
  public static void addFieldName(FlatBufferBuilder builder, int fieldNameOffset) { builder.addOffset(1, fieldNameOffset, 0); }
  public static void addFieldType(FlatBufferBuilder builder, byte fieldType) { builder.addByte(2, fieldType, 0); }
  public static int endScoreBoardSchemaFieldFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

