// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SecurityFbs extends Table {
  public static SecurityFbs getRootAsSecurityFbs(ByteBuffer _bb) { return getRootAsSecurityFbs(_bb, new SecurityFbs()); }
  public static SecurityFbs getRootAsSecurityFbs(ByteBuffer _bb, SecurityFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SecurityFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long sid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int exchangeSid() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String code() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer codeAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public byte securityType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte spreadTableCode() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String currency() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer currencyAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public int lotSize() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int previousClosingPrice() { int o = __offset(18); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int listingDate() { int o = __offset(20); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int conversionRatio() { int o = __offset(22); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int strikePrice() { int o = __offset(24); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int maturity() { int o = __offset(26); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte putOrCall() { int o = __offset(28); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte style() { int o = __offset(30); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long undSid() { int o = __offset(32); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int issuerSid() { int o = __offset(34); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean isAlgo() { int o = __offset(36); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createSecurityFbs(FlatBufferBuilder builder,
      long sid,
      int exchangeSid,
      int codeOffset,
      byte securityType,
      byte spreadTableCode,
      int currencyOffset,
      int lotSize,
      int previousClosingPrice,
      int listingDate,
      int conversionRatio,
      int strikePrice,
      int maturity,
      byte putOrCall,
      byte style,
      long undSid,
      int issuerSid,
      boolean isAlgo) {
    builder.startObject(17);
    SecurityFbs.addUndSid(builder, undSid);
    SecurityFbs.addSid(builder, sid);
    SecurityFbs.addIssuerSid(builder, issuerSid);
    SecurityFbs.addMaturity(builder, maturity);
    SecurityFbs.addStrikePrice(builder, strikePrice);
    SecurityFbs.addConversionRatio(builder, conversionRatio);
    SecurityFbs.addListingDate(builder, listingDate);
    SecurityFbs.addPreviousClosingPrice(builder, previousClosingPrice);
    SecurityFbs.addLotSize(builder, lotSize);
    SecurityFbs.addCurrency(builder, currencyOffset);
    SecurityFbs.addCode(builder, codeOffset);
    SecurityFbs.addExchangeSid(builder, exchangeSid);
    SecurityFbs.addIsAlgo(builder, isAlgo);
    SecurityFbs.addStyle(builder, style);
    SecurityFbs.addPutOrCall(builder, putOrCall);
    SecurityFbs.addSpreadTableCode(builder, spreadTableCode);
    SecurityFbs.addSecurityType(builder, securityType);
    return SecurityFbs.endSecurityFbs(builder);
  }

  public static void startSecurityFbs(FlatBufferBuilder builder) { builder.startObject(17); }
  public static void addSid(FlatBufferBuilder builder, long sid) { builder.addLong(0, sid, 0L); }
  public static void addExchangeSid(FlatBufferBuilder builder, int exchangeSid) { builder.addInt(1, exchangeSid, 0); }
  public static void addCode(FlatBufferBuilder builder, int codeOffset) { builder.addOffset(2, codeOffset, 0); }
  public static void addSecurityType(FlatBufferBuilder builder, byte securityType) { builder.addByte(3, securityType, 0); }
  public static void addSpreadTableCode(FlatBufferBuilder builder, byte spreadTableCode) { builder.addByte(4, spreadTableCode, 0); }
  public static void addCurrency(FlatBufferBuilder builder, int currencyOffset) { builder.addOffset(5, currencyOffset, 0); }
  public static void addLotSize(FlatBufferBuilder builder, int lotSize) { builder.addInt(6, lotSize, 0); }
  public static void addPreviousClosingPrice(FlatBufferBuilder builder, int previousClosingPrice) { builder.addInt(7, previousClosingPrice, 0); }
  public static void addListingDate(FlatBufferBuilder builder, int listingDate) { builder.addInt(8, listingDate, 0); }
  public static void addConversionRatio(FlatBufferBuilder builder, int conversionRatio) { builder.addInt(9, conversionRatio, 0); }
  public static void addStrikePrice(FlatBufferBuilder builder, int strikePrice) { builder.addInt(10, strikePrice, 0); }
  public static void addMaturity(FlatBufferBuilder builder, int maturity) { builder.addInt(11, maturity, 0); }
  public static void addPutOrCall(FlatBufferBuilder builder, byte putOrCall) { builder.addByte(12, putOrCall, 0); }
  public static void addStyle(FlatBufferBuilder builder, byte style) { builder.addByte(13, style, 0); }
  public static void addUndSid(FlatBufferBuilder builder, long undSid) { builder.addLong(14, undSid, 0L); }
  public static void addIssuerSid(FlatBufferBuilder builder, int issuerSid) { builder.addInt(15, issuerSid, 0); }
  public static void addIsAlgo(FlatBufferBuilder builder, boolean isAlgo) { builder.addBoolean(16, isAlgo, false); }
  public static int endSecurityFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

