// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class SecurityTypeFbs {
  private SecurityTypeFbs() { }
  public static final byte STOCK = 0;
  public static final byte WARRANT = 1;
  public static final byte CBBC = 2;
  public static final byte INDEX = 3;
  public static final byte FUTURES = 4;

  public static final String[] names = { "STOCK", "WARRANT", "CBBC", "INDEX", "FUTURES", };

  public static String name(int e) { return names[e]; }
}

