// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class ServiceStatusTypeFbs {
  private ServiceStatusTypeFbs() { }
  public static final byte UP = 0;
  public static final byte DOWN = 1;
  public static final byte INITIALIZING = 2;
  public static final byte WARMING_UP = 3;
  public static final byte HEARTBEAT = 4;

  public static final String[] names = { "UP", "DOWN", "INITIALIZING", "WARMING_UP", "HEARTBEAT", };

  public static String name(int e) { return names[e]; }
}

