// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class ServiceTypeFbs {
  private ServiceTypeFbs() { }
  public static final byte NULL = 0;
  public static final byte RefDataService = 1;
  public static final byte StrategyService = 2;
  public static final byte MarketDataService = 3;
  public static final byte OrderManagementAndExecutionService = 4;
  public static final byte AdminService = 5;
  public static final byte EchoService = 6;
  public static final byte AeronService = 7;
  public static final byte PerformanceService = 8;
  public static final byte DeadLetterService = 9;
  public static final byte DashboardService = 10;
  public static final byte PortfolioAndRiskService = 11;
  public static final byte MarketDataRefreshService = 12;
  public static final byte MarketDataSnapshotService = 13;
  public static final byte LineHandler = 14;
  public static final byte ClientService = 15;
  public static final byte ExchangeService = 16;
  public static final byte OrderAndTradeSnapshotService = 17;
  public static final byte PersistService = 18;
  public static final byte NotificationService = 19;
  public static final byte WarmupService = 20;
  public static final byte PricingService = 21;
  public static final byte PingService = 22;
  public static final byte PongService = 23;
  public static final byte ScoreBoardService = 24;

  public static final String[] names = { "NULL", "RefDataService", "StrategyService", "MarketDataService", "OrderManagementAndExecutionService", "AdminService", "EchoService", "AeronService", "PerformanceService", "DeadLetterService", "DashboardService", "PortfolioAndRiskService", "MarketDataRefreshService", "MarketDataSnapshotService", "LineHandler", "ClientService", "ExchangeService", "OrderAndTradeSnapshotService", "PersistService", "NotificationService", "WarmupService", "PricingService", "PingService", "PongService", "ScoreBoardService", };

  public static String name(int e) { return names[e]; }
}

