// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class SideFbs {
  private SideFbs() { }
  public static final byte BUY = 0;
  public static final byte SELL = 1;

  public static final String[] names = { "BUY", "SELL", };

  public static String name(int e) { return names[e]; }
}

