// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class SpreadStateFbs {
  private SpreadStateFbs() { }
  public static final byte NULL = -128;
  public static final byte NORMAL = 1;
  public static final byte WIDE = 2;
  public static final byte TOO_WIDE = 3;
}

