// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class StrategySwitchTypeFbs {
  private StrategySwitchTypeFbs() { }
  public static final byte NULL = -128;
  public static final byte UNKNOWN = 0;
  public static final byte STRATEGY_PERSIST = 1;
  public static final byte STRATEGY_DAY_ONLY = 2;
  public static final byte SCOREBOARD_PERSIST = 3;
  public static final byte SCOREBOARD_DAY_ONLY = 4;
}

