// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StrategyStatusFbs extends Table {
  public static StrategyStatusFbs getRootAsStrategyStatusFbs(ByteBuffer _bb) { return getRootAsStrategyStatusFbs(_bb, new StrategyStatusFbs()); }
  public static StrategyStatusFbs getRootAsStrategyStatusFbs(ByteBuffer _bb, StrategyStatusFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public StrategyStatusFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long secSid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long strategySid() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public byte status() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createStrategyStatusFbs(FlatBufferBuilder builder,
      long secSid,
      long strategySid,
      byte status) {
    builder.startObject(3);
    StrategyStatusFbs.addStrategySid(builder, strategySid);
    StrategyStatusFbs.addSecSid(builder, secSid);
    StrategyStatusFbs.addStatus(builder, status);
    return StrategyStatusFbs.endStrategyStatusFbs(builder);
  }

  public static void startStrategyStatusFbs(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addSecSid(FlatBufferBuilder builder, long secSid) { builder.addLong(0, secSid, 0L); }
  public static void addStrategySid(FlatBufferBuilder builder, long strategySid) { builder.addLong(1, strategySid, 0L); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(2, status, 0); }
  public static int endStrategyStatusFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

