// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class StrategyParamSourceFbs {
  private StrategyParamSourceFbs() { }
  public static final byte NULL = -128;
  public static final byte STRATEGY_ID = 0;
  public static final byte SECURITY_SID = 1;
  public static final byte UNDERLYING_SECURITY_ID = 2;
  public static final byte ISSUER_SID = 3;
}

