// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class StrategyExplainType {
  private StrategyExplainType() { }
  public static final byte STOCK_WIDESPREAD_BUY_SIGNAL = 1;
  public static final byte STOCK_TIGHTSPREAD_BUY_SIGNAL = 2;
  public static final byte STOP_LOSS_SELL_SIGNAL = 3;
  public static final byte PROFIT_RUN_SELL_SIGNAL = 4;
  public static final byte EXIT_STRATEGY_SELL_SIGNAL = 5;
  public static final byte USER_CAPTURE_PROFIT_SIGNAL = 6;
  public static final byte PREDICTION_BY_WAVG_BUCKET_BUY_SIGNAL = 7;
  public static final byte PREDICTION_BY_WAVG_SPOT_BUY_SIGNAL = 8;
  public static final byte PREDICTION_BY_BID_BUCKET_BUY_SIGNAL = 9;
  public static final byte ISSUER_DOWN_VOL_SELL_SIGNAL = 10;
  public static final byte TO_MAKING_SELL_SIGNAL = 11;
  public static final byte STOP_PROFIT_SELL_SIGNAL = 12;
  public static final byte NON_ISSUER_BID_SELL_SIGNAL = 13;
  public static final byte USER_PLACE_SELL_ORDER_SIGNAL = 14;
  public static final byte QUICK_PROFIT_SELL_SIGNAL = 15;
  public static final byte LARGE_OUTSTANDING_SELL_SIGNAL = 16;
  public static final byte CLOSING_PROFIT_RUN_SELL_SIGNAL = 17;
  public static final byte DELTA_LIMIT_SELL_SIGNAL = 18;

  public static final String[] names = { "STOCK_WIDESPREAD_BUY_SIGNAL", "STOCK_TIGHTSPREAD_BUY_SIGNAL", "STOP_LOSS_SELL_SIGNAL", "PROFIT_RUN_SELL_SIGNAL", "EXIT_STRATEGY_SELL_SIGNAL", "USER_CAPTURE_PROFIT_SIGNAL", "PREDICTION_BY_WAVG_BUCKET_BUY_SIGNAL", "PREDICTION_BY_WAVG_SPOT_BUY_SIGNAL", "PREDICTION_BY_BID_BUCKET_BUY_SIGNAL", "ISSUER_DOWN_VOL_SELL_SIGNAL", "TO_MAKING_SELL_SIGNAL", "STOP_PROFIT_SELL_SIGNAL", "NON_ISSUER_BID_SELL_SIGNAL", "USER_PLACE_SELL_ORDER_SIGNAL", "QUICK_PROFIT_SELL_SIGNAL", "LARGE_OUTSTANDING_SELL_SIGNAL", "CLOSING_PROFIT_RUN_SELL_SIGNAL", "DELTA_LIMIT_SELL_SIGNAL", };

  public static String name(int e) { return names[e - STOCK_WIDESPREAD_BUY_SIGNAL]; }
}

