// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StrategyFieldFbs extends Table {
  public static StrategyFieldFbs getRootAsStrategyFieldFbs(ByteBuffer _bb) { return getRootAsStrategyFieldFbs(_bb, new StrategyFieldFbs()); }
  public static StrategyFieldFbs getRootAsStrategyFieldFbs(ByteBuffer _bb, StrategyFieldFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public StrategyFieldFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int sid() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public byte source() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte type() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public boolean readOnly() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createStrategyFieldFbs(FlatBufferBuilder builder,
      int sid,
      int nameOffset,
      byte source,
      byte type,
      boolean readOnly) {
    builder.startObject(5);
    StrategyFieldFbs.addName(builder, nameOffset);
    StrategyFieldFbs.addSid(builder, sid);
    StrategyFieldFbs.addReadOnly(builder, readOnly);
    StrategyFieldFbs.addType(builder, type);
    StrategyFieldFbs.addSource(builder, source);
    return StrategyFieldFbs.endStrategyFieldFbs(builder);
  }

  public static void startStrategyFieldFbs(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addSid(FlatBufferBuilder builder, int sid) { builder.addInt(0, sid, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addSource(FlatBufferBuilder builder, byte source) { builder.addByte(2, source, 0); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(3, type, 0); }
  public static void addReadOnly(FlatBufferBuilder builder, boolean readOnly) { builder.addBoolean(4, readOnly, false); }
  public static int endStrategyFieldFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

