// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class StrategyStatusTypeFbs {
  private StrategyStatusTypeFbs() { }
  public static final byte OFF = 0;
  public static final byte ACTIVE = 1;
  public static final byte IDLE = 2;
  public static final byte STRATEGY_EXITING = 3;
  public static final byte PRICE_CHECK_EXITING = 4;
  public static final byte NO_CHECK_EXITING = 5;
  public static final byte SEMI_MANUAL_EXITING = 6;
  public static final byte CLOSING_STRATEGY_EXITING = 7;
  public static final byte CLOSING_PRICE_CHECK_EXITING = 8;
  public static final byte ALLOW_SELL_ON_WIDE_SPREAD = 9;
  public static final byte ERROR = 10;
  public static final byte SCOREBOARD_EXITING = 11;

  public static final String[] names = { "OFF", "ACTIVE", "IDLE", "STRATEGY_EXITING", "PRICE_CHECK_EXITING", "NO_CHECK_EXITING", "SEMI_MANUAL_EXITING", "CLOSING_STRATEGY_EXITING", "CLOSING_PRICE_CHECK_EXITING", "ALLOW_SELL_ON_WIDE_SPREAD", "ERROR", "SCOREBOARD_EXITING", };

  public static String name(int e) { return names[e]; }
}

