// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StrategyParamValueFbs extends Table {
  public static StrategyParamValueFbs getRootAsStrategyParamValueFbs(ByteBuffer _bb) { return getRootAsStrategyParamValueFbs(_bb, new StrategyParamValueFbs()); }
  public static StrategyParamValueFbs getRootAsStrategyParamValueFbs(ByteBuffer _bb, StrategyParamValueFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public StrategyParamValueFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int fieldSid() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String stringValue() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer stringValueAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public long longValue() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createStrategyParamValueFbs(FlatBufferBuilder builder,
      int fieldSid,
      int stringValueOffset,
      long longValue) {
    builder.startObject(3);
    StrategyParamValueFbs.addLongValue(builder, longValue);
    StrategyParamValueFbs.addStringValue(builder, stringValueOffset);
    StrategyParamValueFbs.addFieldSid(builder, fieldSid);
    return StrategyParamValueFbs.endStrategyParamValueFbs(builder);
  }

  public static void startStrategyParamValueFbs(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addFieldSid(FlatBufferBuilder builder, int fieldSid) { builder.addInt(0, fieldSid, 0); }
  public static void addStringValue(FlatBufferBuilder builder, int stringValueOffset) { builder.addOffset(1, stringValueOffset, 0); }
  public static void addLongValue(FlatBufferBuilder builder, long longValue) { builder.addLong(2, longValue, 0L); }
  public static int endStrategyParamValueFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

