// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class StrategyExitMode {
  private StrategyExitMode() { }
  public static final byte NULL = -128;
  public static final byte NO_EXIT = 1;
  public static final byte STRATEGY_EXIT = 2;
  public static final byte PRICE_CHECK_EXIT = 3;
  public static final byte NO_CHECK_EXIT = 4;
  public static final byte SEMI_MANUAL_EXIT = 5;
  public static final byte CLOSING_STRATEGY_EXIT = 6;
  public static final byte CLOSING_PRICE_CHECK_EXIT = 7;
  public static final byte ERROR = 8;
  public static final byte SCOREBOARD_EXIT = 9;
}

