// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class StrategyParamTypeFbs {
  private StrategyParamTypeFbs() { }
  public static final byte STRING = 1;
  public static final byte LONG = 2;

  public static final String[] names = { "STRING", "LONG", };

  public static String name(int e) { return names[e - STRING]; }
}

