// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StrategyTypeFbs extends Table {
  public static StrategyTypeFbs getRootAsStrategyTypeFbs(ByteBuffer _bb) { return getRootAsStrategyTypeFbs(_bb, new StrategyTypeFbs()); }
  public static StrategyTypeFbs getRootAsStrategyTypeFbs(ByteBuffer _bb, StrategyTypeFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public StrategyTypeFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long sid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public StrategyFieldFbs fields(int j) { return fields(new StrategyFieldFbs(), j); }
  public StrategyFieldFbs fields(StrategyFieldFbs obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int fieldsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }

  public static int createStrategyTypeFbs(FlatBufferBuilder builder,
      long sid,
      int nameOffset,
      int fieldsOffset) {
    builder.startObject(3);
    StrategyTypeFbs.addSid(builder, sid);
    StrategyTypeFbs.addFields(builder, fieldsOffset);
    StrategyTypeFbs.addName(builder, nameOffset);
    return StrategyTypeFbs.endStrategyTypeFbs(builder);
  }

  public static void startStrategyTypeFbs(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addSid(FlatBufferBuilder builder, long sid) { builder.addLong(0, sid, 0L); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addFields(FlatBufferBuilder builder, int fieldsOffset) { builder.addOffset(2, fieldsOffset, 0); }
  public static int createFieldsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFieldsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endStrategyTypeFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

