// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class StrategyTriggerType {
  private StrategyTriggerType() { }
  public static final byte VELOCITY_5MS = 1;
  public static final byte VELOCITY_10MS = 2;
  public static final byte ALLOW_ALL = 3;

  public static final String[] names = { "VELOCITY_5MS", "VELOCITY_10MS", "ALLOW_ALL", };

  public static String name(int e) { return names[e - VELOCITY_5MS]; }
}

