// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StrategyIssuerUndParametersFbs extends Table {
  public static StrategyIssuerUndParametersFbs getRootAsStrategyIssuerUndParametersFbs(ByteBuffer _bb) { return getRootAsStrategyIssuerUndParametersFbs(_bb, new StrategyIssuerUndParametersFbs()); }
  public static StrategyIssuerUndParametersFbs getRootAsStrategyIssuerUndParametersFbs(ByteBuffer _bb, StrategyIssuerUndParametersFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public StrategyIssuerUndParametersFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long strategyId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int issuerSid() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long undSid() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long issuerUndSid() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public StrategyParamValueFbs parameters(int j) { return parameters(new StrategyParamValueFbs(), j); }
  public StrategyParamValueFbs parameters(StrategyParamValueFbs obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int parametersLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }

  public static int createStrategyIssuerUndParametersFbs(FlatBufferBuilder builder,
      long strategyId,
      int issuerSid,
      long undSid,
      long issuerUndSid,
      int parametersOffset) {
    builder.startObject(5);
    StrategyIssuerUndParametersFbs.addIssuerUndSid(builder, issuerUndSid);
    StrategyIssuerUndParametersFbs.addUndSid(builder, undSid);
    StrategyIssuerUndParametersFbs.addStrategyId(builder, strategyId);
    StrategyIssuerUndParametersFbs.addParameters(builder, parametersOffset);
    StrategyIssuerUndParametersFbs.addIssuerSid(builder, issuerSid);
    return StrategyIssuerUndParametersFbs.endStrategyIssuerUndParametersFbs(builder);
  }

  public static void startStrategyIssuerUndParametersFbs(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addStrategyId(FlatBufferBuilder builder, long strategyId) { builder.addLong(0, strategyId, 0L); }
  public static void addIssuerSid(FlatBufferBuilder builder, int issuerSid) { builder.addInt(1, issuerSid, 0); }
  public static void addUndSid(FlatBufferBuilder builder, long undSid) { builder.addLong(2, undSid, 0L); }
  public static void addIssuerUndSid(FlatBufferBuilder builder, long issuerUndSid) { builder.addLong(3, issuerUndSid, 0L); }
  public static void addParameters(FlatBufferBuilder builder, int parametersOffset) { builder.addOffset(4, parametersOffset, 0); }
  public static int createParametersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startParametersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endStrategyIssuerUndParametersFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

