// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class TimeInForceFbs {
  private TimeInForceFbs() { }
  public static final byte DAY = 0;
  public static final byte GOOD_TILL_CANCEL = 1;
  public static final byte FILL_AND_KILL = 3;
  public static final byte GOOD_TILL_DATE = 6;

  public static final String[] names = { "DAY", "GOOD_TILL_CANCEL", "", "FILL_AND_KILL", "", "", "GOOD_TILL_DATE", };

  public static String name(int e) { return names[e]; }
}

