// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TradeFbs extends Table {
  public static TradeFbs getRootAsTradeFbs(ByteBuffer _bb) { return getRootAsTradeFbs(_bb, new TradeFbs()); }
  public static TradeFbs getRootAsTradeFbs(ByteBuffer _bb, TradeFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TradeFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int channelId() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long channelSnapshotSeq() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long createTime() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long updateTime() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int tradeSid() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int orderSid() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long secSid() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public byte side() { int o = __offset(18); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int orderId() { int o = __offset(20); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte status() { int o = __offset(22); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte tradeStatus() { int o = __offset(24); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int cumulativeQty() { int o = __offset(26); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int leavesQty() { int o = __offset(28); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String executionId() { int o = __offset(30); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer executionIdAsByteBuffer() { return __vector_as_bytebuffer(30, 1); }
  public int executionQty() { int o = __offset(32); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int executionPrice() { int o = __offset(34); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createTradeFbs(FlatBufferBuilder builder,
      int channelId,
      long channelSnapshotSeq,
      long createTime,
      long updateTime,
      int tradeSid,
      int orderSid,
      long secSid,
      byte side,
      int orderId,
      byte status,
      byte tradeStatus,
      int cumulativeQty,
      int leavesQty,
      int executionIdOffset,
      int executionQty,
      int executionPrice) {
    builder.startObject(16);
    TradeFbs.addSecSid(builder, secSid);
    TradeFbs.addUpdateTime(builder, updateTime);
    TradeFbs.addCreateTime(builder, createTime);
    TradeFbs.addChannelSnapshotSeq(builder, channelSnapshotSeq);
    TradeFbs.addExecutionPrice(builder, executionPrice);
    TradeFbs.addExecutionQty(builder, executionQty);
    TradeFbs.addExecutionId(builder, executionIdOffset);
    TradeFbs.addLeavesQty(builder, leavesQty);
    TradeFbs.addCumulativeQty(builder, cumulativeQty);
    TradeFbs.addOrderId(builder, orderId);
    TradeFbs.addOrderSid(builder, orderSid);
    TradeFbs.addTradeSid(builder, tradeSid);
    TradeFbs.addChannelId(builder, channelId);
    TradeFbs.addTradeStatus(builder, tradeStatus);
    TradeFbs.addStatus(builder, status);
    TradeFbs.addSide(builder, side);
    return TradeFbs.endTradeFbs(builder);
  }

  public static void startTradeFbs(FlatBufferBuilder builder) { builder.startObject(16); }
  public static void addChannelId(FlatBufferBuilder builder, int channelId) { builder.addInt(0, channelId, 0); }
  public static void addChannelSnapshotSeq(FlatBufferBuilder builder, long channelSnapshotSeq) { builder.addLong(1, channelSnapshotSeq, 0L); }
  public static void addCreateTime(FlatBufferBuilder builder, long createTime) { builder.addLong(2, createTime, 0L); }
  public static void addUpdateTime(FlatBufferBuilder builder, long updateTime) { builder.addLong(3, updateTime, 0L); }
  public static void addTradeSid(FlatBufferBuilder builder, int tradeSid) { builder.addInt(4, tradeSid, 0); }
  public static void addOrderSid(FlatBufferBuilder builder, int orderSid) { builder.addInt(5, orderSid, 0); }
  public static void addSecSid(FlatBufferBuilder builder, long secSid) { builder.addLong(6, secSid, 0L); }
  public static void addSide(FlatBufferBuilder builder, byte side) { builder.addByte(7, side, 0); }
  public static void addOrderId(FlatBufferBuilder builder, int orderId) { builder.addInt(8, orderId, 0); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(9, status, 0); }
  public static void addTradeStatus(FlatBufferBuilder builder, byte tradeStatus) { builder.addByte(10, tradeStatus, 0); }
  public static void addCumulativeQty(FlatBufferBuilder builder, int cumulativeQty) { builder.addInt(11, cumulativeQty, 0); }
  public static void addLeavesQty(FlatBufferBuilder builder, int leavesQty) { builder.addInt(12, leavesQty, 0); }
  public static void addExecutionId(FlatBufferBuilder builder, int executionIdOffset) { builder.addOffset(13, executionIdOffset, 0); }
  public static void addExecutionQty(FlatBufferBuilder builder, int executionQty) { builder.addInt(14, executionQty, 0); }
  public static void addExecutionPrice(FlatBufferBuilder builder, int executionPrice) { builder.addInt(15, executionPrice, 0); }
  public static int endTradeFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

