// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class TradeStatusFbs {
  private TradeStatusFbs() { }
  public static final byte NEW = 0;
  public static final byte CANCELLED = 1;

  public static final String[] names = { "NEW", "CANCELLED", };

  public static String name(int e) { return names[e]; }
}

