// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class UpdateActionFbs {
  private UpdateActionFbs() { }
  public static final byte NEW = 0;
  public static final byte CHANGE = 1;
  public static final byte DELETE = 2;
  public static final byte CLEAR = 3;

  public static final String[] names = { "NEW", "CHANGE", "DELETE", "CLEAR", };

  public static String name(int e) { return names[e]; }
}

