// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class VerifiedDoubleFbs extends Table {
  public static VerifiedDoubleFbs getRootAsVerifiedDoubleFbs(ByteBuffer _bb) { return getRootAsVerifiedDoubleFbs(_bb, new VerifiedDoubleFbs()); }
  public static VerifiedDoubleFbs getRootAsVerifiedDoubleFbs(ByteBuffer _bb, VerifiedDoubleFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public VerifiedDoubleFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double value() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public boolean verified() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createVerifiedDoubleFbs(FlatBufferBuilder builder,
      double value,
      boolean verified) {
    builder.startObject(2);
    VerifiedDoubleFbs.addValue(builder, value);
    VerifiedDoubleFbs.addVerified(builder, verified);
    return VerifiedDoubleFbs.endVerifiedDoubleFbs(builder);
  }

  public static void startVerifiedDoubleFbs(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addValue(FlatBufferBuilder builder, double value) { builder.addDouble(0, value, 0.0); }
  public static void addVerified(FlatBufferBuilder builder, boolean verified) { builder.addBoolean(1, verified, false); }
  public static int endVerifiedDoubleFbs(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

