// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class VolumeClusterDirectionTypeFbs {
  private VolumeClusterDirectionTypeFbs() { }
  public static final byte UNKNOWN = 0;
  public static final byte UP = 1;
  public static final byte DOWN = 2;
  public static final byte NEUTRAL = 3;

  public static final String[] names = { "UNKNOWN", "UP", "DOWN", "NEUTRAL", };

  public static String name(int e) { return names[e]; }
}

