// automatically generated by the FlatBuffers compiler, do not modify

package com.lunar.message.io.fbs;

public final class VolumeClusterTypeFbs {
  private VolumeClusterTypeFbs() { }
  public static final byte NORMAL = 0;
  public static final byte HIGH = 1;
  public static final byte POC = 2;

  public static final String[] names = { "NORMAL", "HIGH", "POC", };

  public static String name(int e) { return names[e]; }
}

