/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lunar_marketdata_hkex_CtpMduApi */

#ifndef _Included_com_lunar_marketdata_hkex_CtpMduApi
#define _Included_com_lunar_marketdata_hkex_CtpMduApi
#ifdef __cplusplus
extern "C" {
#endif
#undef com_lunar_marketdata_hkex_CtpMduApi_NA
#define com_lunar_marketdata_hkex_CtpMduApi_NA 0L
#undef com_lunar_marketdata_hkex_CtpMduApi_CLOSE
#define com_lunar_marketdata_hkex_CtpMduApi_CLOSE 1L
#undef com_lunar_marketdata_hkex_CtpMduApi_CLOSING
#define com_lunar_marketdata_hkex_CtpMduApi_CLOSING 2L
#undef com_lunar_marketdata_hkex_CtpMduApi_HALT
#define com_lunar_marketdata_hkex_CtpMduApi_HALT 4L
#undef com_lunar_marketdata_hkex_CtpMduApi_FAST_MARKET
#define com_lunar_marketdata_hkex_CtpMduApi_FAST_MARKET 8L
#undef com_lunar_marketdata_hkex_CtpMduApi_PRE_CLOSING
#define com_lunar_marketdata_hkex_CtpMduApi_PRE_CLOSING 16L
#undef com_lunar_marketdata_hkex_CtpMduApi_PRE_OPENING
#define com_lunar_marketdata_hkex_CtpMduApi_PRE_OPENING 32L
#undef com_lunar_marketdata_hkex_CtpMduApi_OPENING
#define com_lunar_marketdata_hkex_CtpMduApi_OPENING 64L
#undef com_lunar_marketdata_hkex_CtpMduApi_OPEN
#define com_lunar_marketdata_hkex_CtpMduApi_OPEN 128L
#undef com_lunar_marketdata_hkex_CtpMduApi_MAX
#define com_lunar_marketdata_hkex_CtpMduApi_MAX 129L
#undef com_lunar_marketdata_hkex_CtpMduApi_CONNECTED
#define com_lunar_marketdata_hkex_CtpMduApi_CONNECTED 0L
#undef com_lunar_marketdata_hkex_CtpMduApi_CONNECTING
#define com_lunar_marketdata_hkex_CtpMduApi_CONNECTING 1L
#undef com_lunar_marketdata_hkex_CtpMduApi_DISCONNECTING
#define com_lunar_marketdata_hkex_CtpMduApi_DISCONNECTING 2L
#undef com_lunar_marketdata_hkex_CtpMduApi_DISCONNECTED
#define com_lunar_marketdata_hkex_CtpMduApi_DISCONNECTED 3L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_UNKNOWN
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_UNKNOWN 0L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_UNSUPPORTED
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_UNSUPPORTED 1L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_NOT_READY
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_NOT_READY 2L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_NOT_CONNECTED
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_NOT_CONNECTED 4L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_NOT_LOGGED_IN
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_NOT_LOGGED_IN 8L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_ALREADY_CONNECTED
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_ALREADY_CONNECTED 16L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_ALREADY_LOGGED_IN
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_ALREADY_LOGGED_IN 32L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_ALREADY_SUBSCRIBED
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_ALREADY_SUBSCRIBED 64L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_INVALID_ACCOUNT
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_INVALID_ACCOUNT 128L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_INVALID_FILTER
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_INVALID_FILTER 256L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_INVALID_DATA
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_INVALID_DATA 512L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_REJECTED
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_REJECTED 1024L
#undef com_lunar_marketdata_hkex_CtpMduApi_ERROR_BUSY
#define com_lunar_marketdata_hkex_CtpMduApi_ERROR_BUSY 2048L
/*
 * Class:     com_lunar_marketdata_hkex_CtpMduApi
 * Method:    initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_marketdata_hkex_CtpMduApi_initialize
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jobject, jobject, jobject, jint);

/*
 * Class:     com_lunar_marketdata_hkex_CtpMduApi
 * Method:    registerSecurity
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_marketdata_hkex_CtpMduApi_registerSecurity
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_lunar_marketdata_hkex_CtpMduApi
 * Method:    registerSecurity
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_marketdata_hkex_CtpMduApi_registerHsiFutures
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_lunar_marketdata_hkex_CtpMduApi
 * Method:    registerSecurity
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_marketdata_hkex_CtpMduApi_registerHsceiFutures
  (JNIEnv *, jobject, jlong, jstring);


/*
 * Class:     com_lunar_marketdata_hkex_CtpMduApi
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lunar_marketdata_hkex_CtpMduApi_close
  (JNIEnv *, jobject);

/*
 * Class:     com_lunar_marketdata_hkex_CtpMduApi
 * Method:    requestSnapshot 
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_marketdata_hkex_CtpMduApi_requestSnapshot
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_lunar_marketdata_hkex_CtpMduApi
 * Method:    getNanoOfDay
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_lunar_marketdata_hkex_CtpMduApi_getNanoOfDay
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
