/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lunar_order_hkex_ocg_CtpOcgApi */

#ifndef _Included_com_lunar_order_hkex_ocg_CtpOcgApi
#define _Included_com_lunar_order_hkex_ocg_CtpOcgApi
#ifdef __cplusplus
extern "C" {
#endif
#undef com_lunar_order_hkex_ocg_CtpOcgApi_SELL
#define com_lunar_order_hkex_ocg_CtpOcgApi_SELL 1L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_BUY
#define com_lunar_order_hkex_ocg_CtpOcgApi_BUY 2L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_MARKET
#define com_lunar_order_hkex_ocg_CtpOcgApi_MARKET 1L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_LIMIT
#define com_lunar_order_hkex_ocg_CtpOcgApi_LIMIT 2L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_MARKET_TO_LIMIT
#define com_lunar_order_hkex_ocg_CtpOcgApi_MARKET_TO_LIMIT 4L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_LIMIT_TO_MARKET
#define com_lunar_order_hkex_ocg_CtpOcgApi_LIMIT_TO_MARKET 5L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ON_OPEN
#define com_lunar_order_hkex_ocg_CtpOcgApi_ON_OPEN 16L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ON_CLOSE
#define com_lunar_order_hkex_ocg_CtpOcgApi_ON_CLOSE 32L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_STOP_MARKET
#define com_lunar_order_hkex_ocg_CtpOcgApi_STOP_MARKET 64L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_STOP_LIMIT
#define com_lunar_order_hkex_ocg_CtpOcgApi_STOP_LIMIT 128L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ICEBERG
#define com_lunar_order_hkex_ocg_CtpOcgApi_ICEBERG 256L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_AUCTION_MARKET
#define com_lunar_order_hkex_ocg_CtpOcgApi_AUCTION_MARKET 1024L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_AUCTION_LIMIT
#define com_lunar_order_hkex_ocg_CtpOcgApi_AUCTION_LIMIT 2048L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_AVERAGE
#define com_lunar_order_hkex_ocg_CtpOcgApi_AVERAGE 4096L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ONE_CANCELS_THE_OTHER
#define com_lunar_order_hkex_ocg_CtpOcgApi_ONE_CANCELS_THE_OTHER 8192L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_PEGGED_MARKET
#define com_lunar_order_hkex_ocg_CtpOcgApi_PEGGED_MARKET 32768L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_PEGGED_PRIMARY
#define com_lunar_order_hkex_ocg_CtpOcgApi_PEGGED_PRIMARY 65536L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_PEGGED_MID
#define com_lunar_order_hkex_ocg_CtpOcgApi_PEGGED_MID 131072L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_FILL_OR_KILL
#define com_lunar_order_hkex_ocg_CtpOcgApi_FILL_OR_KILL 1L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ALL_OR_NONE
#define com_lunar_order_hkex_ocg_CtpOcgApi_ALL_OR_NONE 2L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_IMMEDIATE_OR_CANCEL
#define com_lunar_order_hkex_ocg_CtpOcgApi_IMMEDIATE_OR_CANCEL 4L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_IN_SESSION
#define com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_IN_SESSION 8L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_TILL_CANCELLED
#define com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_TILL_CANCELLED 16L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_TILL_DATE
#define com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_TILL_DATE 32L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_FOR_DAY
#define com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_FOR_DAY 64L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_AT_THE_OPENING
#define com_lunar_order_hkex_ocg_CtpOcgApi_AT_THE_OPENING 128L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_TILL_TIME
#define com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_TILL_TIME 256L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_AT_THE_CLOSE
#define com_lunar_order_hkex_ocg_CtpOcgApi_AT_THE_CLOSE 512L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_FOR_INTRADAY_AUCTION
#define com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_FOR_INTRADAY_AUCTION 1024L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_FOR_AUCTION
#define com_lunar_order_hkex_ocg_CtpOcgApi_GOOD_FOR_AUCTION 2048L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_NEW
#define com_lunar_order_hkex_ocg_CtpOcgApi_NEW 48L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_PARTIALLY_FILLED
#define com_lunar_order_hkex_ocg_CtpOcgApi_PARTIALLY_FILLED 49L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_FILLED
#define com_lunar_order_hkex_ocg_CtpOcgApi_FILLED 50L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_DONE_FOR_DAY
#define com_lunar_order_hkex_ocg_CtpOcgApi_DONE_FOR_DAY 51L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_CANCELED
#define com_lunar_order_hkex_ocg_CtpOcgApi_CANCELED 52L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_REPLACED
#define com_lunar_order_hkex_ocg_CtpOcgApi_REPLACED 53L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_PENDING_CANCEL
#define com_lunar_order_hkex_ocg_CtpOcgApi_PENDING_CANCEL 54L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_STOPPED
#define com_lunar_order_hkex_ocg_CtpOcgApi_STOPPED 55L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_REJECTED
#define com_lunar_order_hkex_ocg_CtpOcgApi_REJECTED 56L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_SUSPENDED
#define com_lunar_order_hkex_ocg_CtpOcgApi_SUSPENDED 57L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_PENDING_NEW
#define com_lunar_order_hkex_ocg_CtpOcgApi_PENDING_NEW 65L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_CALCULATED
#define com_lunar_order_hkex_ocg_CtpOcgApi_CALCULATED 66L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_EXPIRED
#define com_lunar_order_hkex_ocg_CtpOcgApi_EXPIRED 67L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ACCEPTED_FOR_BIDDING
#define com_lunar_order_hkex_ocg_CtpOcgApi_ACCEPTED_FOR_BIDDING 68L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_PENDING_REPLACE
#define com_lunar_order_hkex_ocg_CtpOcgApi_PENDING_REPLACE 69L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_UNKNOWN
#define com_lunar_order_hkex_ocg_CtpOcgApi_UNKNOWN 70L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_CONNECTED
#define com_lunar_order_hkex_ocg_CtpOcgApi_CONNECTED 0L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_CONNECTING
#define com_lunar_order_hkex_ocg_CtpOcgApi_CONNECTING 1L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_DISCONNECTING
#define com_lunar_order_hkex_ocg_CtpOcgApi_DISCONNECTING 2L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_DISCONNECTED
#define com_lunar_order_hkex_ocg_CtpOcgApi_DISCONNECTED 3L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_UNKNOWN
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_UNKNOWN 0L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_UNSUPPORTED
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_UNSUPPORTED 1L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_NOT_READY
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_NOT_READY 2L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_NOT_CONNECTED
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_NOT_CONNECTED 4L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_NOT_LOGGED_IN
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_NOT_LOGGED_IN 8L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_ALREADY_CONNECTED
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_ALREADY_CONNECTED 16L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_ALREADY_LOGGED_IN
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_ALREADY_LOGGED_IN 32L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_ALREADY_SUBSCRIBED
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_ALREADY_SUBSCRIBED 64L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_INVALID_ACCOUNT
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_INVALID_ACCOUNT 128L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_INVALID_FILTER
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_INVALID_FILTER 256L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_INVALID_DATA
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_INVALID_DATA 512L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_REJECTED
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_REJECTED 1024L
#undef com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_BUSY
#define com_lunar_order_hkex_ocg_CtpOcgApi_ERROR_BUSY 2048L
/*
 * Class:     com_lunar_order_hkex_ocg_CtpOcgApi
 * Method:    initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_order_hkex_ocg_CtpOcgApi_initialize
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint, jint);

/*
 * Class:     com_lunar_order_hkex_ocg_CtpOcgApi
 * Method:    setMode
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_order_hkex_ocg_CtpOcgApi_setMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_lunar_order_hkex_ocg_CtpOcgApi
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lunar_order_hkex_ocg_CtpOcgApi_close
  (JNIEnv *, jobject);

/*
 * Class:     com_lunar_order_hkex_ocg_CtpOcgApi
 * Method:    endRecovery
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_order_hkex_ocg_CtpOcgApi_endRecovery
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_lunar_order_hkex_ocg_CtpOcgApi
 * Method:    addOrder
 * Signature: (JIJIIIIIZ)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_order_hkex_ocg_CtpOcgApi_addOrder
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     com_lunar_order_hkex_ocg_CtpOcgApi
 * Method:    cancelOrder
 * Signature: (JLjava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_order_hkex_ocg_CtpOcgApi_cancelOrder
  (JNIEnv *, jobject, jlong, jstring, jlong, jint);

/*
 * Class:     com_lunar_order_hkex_ocg_CtpOcgApi
 * Method:    massCancelAll
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_order_hkex_ocg_CtpOcgApi_massCancelAll
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_lunar_order_hkex_ocg_CtpOcgApi
 * Method:    massCancelBySecurity
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_order_hkex_ocg_CtpOcgApi_massCancelBySecurity
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_lunar_order_hkex_ocg_CtpOcgApi
 * Method:    massCancelBySide
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_order_hkex_ocg_CtpOcgApi_massCancelBySide
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_lunar_order_hkex_ocg_CtpOcgApi
 * Method:    displayOrderInfo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_lunar_order_hkex_ocg_CtpOcgApi_displayOrderInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_lunar_order_hkex_ocg_CtpOcgApi
 * Method:    displayAllOrderInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lunar_order_hkex_ocg_CtpOcgApi_displayAllOrderInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
