/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lunar_util_NativeThreadInfo */

#ifndef _Included_com_lunar_util_NativeThreadInfo
#define _Included_com_lunar_util_NativeThreadInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lunar_util_NativeThreadInfo
 * Method:    getTid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lunar_util_NativeThreadInfo_getTid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
