tiger {
	lunar.system.id = 1
    lunar.service.admin {
        create = true
        sinkId = 1
    }
    lunar.aeron {
        transport = "udp"
        hostname = ${lunar.prop.host}
        port = 55160
        streamId = 1
        aeronDir = ${lunar.prop.aeronDir}
    }    
}

lunar {
	system {
		id = -1
	}
    prop {
        host = ${lunar.host}
        port = ${lunar.port}
        aeronDir = ${lunar.aeronDir}
    }
    numServiceInstances = 12
    aeron {
        transport = "udp"
        port = 0
        streamId = -1
        aeronDir = ""
    }
    service {
        admin {
            # do not override the name of admin, the name of the admin of each system
            # must be same in order for broadcasting to work properly 
            name = "lunarAdmin"
            routerName = "lunarAdminRouter"
            type = "AdminService"
            description = "admin service"
            create = false
            queueSize = 1024
        }
        refData {
            type = "RefDataService"
            description = "reference data service"
            create = false
            queueSize = 1024
        }
        aeron {
            type = "AeronService"
            description = "aeron receiver (may include media driver)"
            create = false
            createMediaDriver = false
            channel = "udp://localhost:00000"
            streamId = 1
            aeronDir = ""
        }
        strategy {
            type = "StrategyService"
            description = "strategy service"
            create = false
            queueSize = 1024
        }
        orderManagement {
            type = "OrderManagementAndExecutionService"
            description = "order management and execution service"
            create = false
            queueSize = 1024
        }
        marketData {
            type = "MarketDataService"
            description = "market data service"
            create = false
            queueSize = 1024
        }
        perf {
            type = "PerformanceService"
            description = "performance service"
            create = false
            queueSize = 1024
        }
    }
    messaging {
        frameSize = 128
        command {
            timeout = 5s
        }
        request {
            timeout = 5s
            retry {
                initDelay = 5s
                delayGrowth = "CONSTANT"
                maxRetryAttempts = -1
            }
            requestType {
            }
        }
    }
    timerService {
        tickDuration = 100ms
        ticksPerWheel = 256
    }
    logging {
        folder = ""
        archiveOnStart = false
        archiveFolder = ""
        journalFolder = "journal";
        journalArchiveFolder = "journal_archive";
    }
}
