package com.lunar.fsm.cutloss;

public enum StateTransitionEvent {
	UND_WIDE,
	UND_TIGHT,
	DERIV_MM_CHANGE,
	DERIV_MM_CHANGE_COMPLETE,
	FAIL,
	BUY_DETECTED,
	SELL_DETECTED,
	TIMEOUT,
	NULL,
	START_UND_WIDE,
	START_UND_TIGHT, 
	READY,
	WAIT,
	UNEXPLAINABLE_DOWNWARD_MOVE,
	EXPLAINABLE
}