/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lunar_pricing_QuantLibAdaptor */

#ifndef _Included_com_lunar_pricing_QuantLibAdaptor
#define _Included_com_lunar_pricing_QuantLibAdaptor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_lunar_pricing_QuantLibAdaptor_FAIR_INDEX
#define com_lunar_pricing_QuantLibAdaptor_FAIR_INDEX 0L
#undef com_lunar_pricing_QuantLibAdaptor_DELTA_INDEX
#define com_lunar_pricing_QuantLibAdaptor_DELTA_INDEX 1L
#undef com_lunar_pricing_QuantLibAdaptor_VEGA_INDEX
#define com_lunar_pricing_QuantLibAdaptor_VEGA_INDEX 2L
#undef com_lunar_pricing_QuantLibAdaptor_IVOL_INDEX
#define com_lunar_pricing_QuantLibAdaptor_IVOL_INDEX 3L
/*
 * Class:     com_lunar_pricing_QuantLibAdaptor
 * Method:    initialize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_pricing_QuantLibAdaptor_initialize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_lunar_pricing_QuantLibAdaptor
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lunar_pricing_QuantLibAdaptor_close
  (JNIEnv *, jobject);

/*
 * Class:     com_lunar_pricing_QuantLibAdaptor
 * Method:    createDividendCurve
 * Signature: (J[I[J)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_pricing_QuantLibAdaptor_createDividendCurve
  (JNIEnv *, jobject, jlong, jintArray, jlongArray);

/*
 * Class:     com_lunar_pricing_QuantLibAdaptor
 * Method:    createYieldCurve
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_pricing_QuantLibAdaptor_createYieldCurve
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_lunar_pricing_QuantLibAdaptor
 * Method:    addEuroOption
 * Signature: (JJJZI)I
 */
JNIEXPORT jint JNICALL Java_com_lunar_pricing_QuantLibAdaptor_addEuroOption
  (JNIEnv *, jobject, jlong, jlong, jlong, jboolean, jint);

/*
 * Class:     com_lunar_pricing_QuantLibAdaptor
 * Method:    priceEuroOption
 * Signature: (JJII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_lunar_pricing_QuantLibAdaptor_priceEuroOption
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
